from __future__ import annotations

from datetime import UTC, date, datetime
from unittest.mock import patch
from uuid import uuid4

import pytest
from sqlalchemy import text

from app.api.authentication import get_authenticated_principal
from app.application.administrativo.authentication import AuthenticatedPrincipal
from app.application.administrativo.authorization import (
    AdministrativeAuthorizationDecision,
)
from app.application.administrativo.services.obtener_configuracion_calendario_comercial_query_service import (
    ConfiguracionCalendarioComercialIncompleta,
    ConfiguracionCalendarioComercialInconsistente,
    ObtenerConfiguracionCalendarioComercialQueryService,
)
from app.infrastructure.persistence.repositories.calendario_comercial_query_repository import (
    CalendarioComercialQueryRepository,
)


ENDPOINT = "/api/v1/administrativo/configuracion/calendario-comercial"
CIERRE = "DIA_CIERRE_COMERCIAL"
VENCIMIENTO = "DIA_VENCIMIENTO_PREDETERMINADO_CUOTAS"


def _principal() -> AuthenticatedPrincipal:
    # El código deliberadamente no es ADMINISTRADOR_SISTEMA: autoriza el grant.
    return AuthenticatedPrincipal(
        id_usuario=1,
        codigo_usuario="ROL-ALTERNATIVO",
        login="calendario-test",
        id_sesion=uuid4(),
        mecanismo_autenticacion="SESION_SERVIDOR",
        autenticado_en=datetime.now(UTC).replace(tzinfo=None),
        id_instalacion_origen_sesion=1,
        id_sucursal_operativa=None,
    )


def _grant(client):
    client.app.dependency_overrides[get_authenticated_principal] = _principal
    return patch(
        "app.api.administrative_authorization.AdministrativeAuthorizationService.authorize",
        return_value=AdministrativeAuthorizationDecision.GRANTED,
    )


def _root(db_session, version: int = 1, fixture_id: int = 483_000_001) -> None:
    # La PK es GENERATED BY DEFAULT: un ID explícito mantiene el fixture aislado
    # de la sequence global, que no retrocede con el rollback transaccional.
    db_session.execute(
        text(
            "INSERT INTO configuracion_calendario_comercial("
            "id_configuracion_calendario_comercial, version_registro) "
            "VALUES (:fixture_id, :version)"
        ),
        {"fixture_id": fixture_id, "version": version},
    )


def _historical_root(db_session, fixture_id: int) -> None:
    _root(db_session, fixture_id=fixture_id)
    db_session.execute(
        text("""
            UPDATE configuracion_calendario_comercial
               SET deleted_at = CURRENT_TIMESTAMP
             WHERE id_configuracion_calendario_comercial = :fixture_id
        """),
        {"fixture_id": fixture_id},
    )


def _value(
    db_session,
    code: str,
    value: str,
    start: str,
    end: str | None,
    *,
    current: bool = False,
) -> None:
    db_session.execute(
        text("""
            INSERT INTO valor_parametro(
                id_parametro_sistema, valor_parametro, es_valor_vigente,
                fecha_desde, fecha_hasta
            )
            SELECT id_parametro_sistema, :value, :current, :start, :end
              FROM parametro_sistema WHERE codigo_parametro = :code
        """),
        {"code": code, "value": value, "current": current, "start": start, "end": end},
    )


def _period(db_session, start: str, end: str | None, cierre=10, vencimiento=20):
    _value(db_session, CIERRE, str(cierre), start, end)
    _value(db_session, VENCIMIENTO, str(vencimiento), start, end)


def _service(db_session):
    return ObtenerConfiguracionCalendarioComercialQueryService(
        CalendarioComercialQueryRepository(db_session)
    )


def test_query_service_snapshot_temporal_sin_principal_http(db_session):
    _root(db_session)
    _period(db_session, "2026-01-01", "2026-03-01", 8, 18)
    _period(db_session, "2026-03-01", None, 12, 22)

    limite_inferior = _service(db_session).obtener(date(2026, 1, 1))
    limite_superior = _service(db_session).obtener(date(2026, 3, 1))

    assert limite_inferior.dia_cierre_comercial == 8
    assert limite_inferior.fecha_hasta == datetime(2026, 3, 1)
    assert limite_superior.dia_cierre_comercial == 12
    assert limite_superior.dia_vencimiento_predeterminado_cuotas == 22
    assert limite_superior.fecha_hasta is None
    assert limite_superior.version_agregada == 1


def test_fixture_raiz_no_consume_identity_sequence(db_session):
    sequence_name = db_session.execute(
        text("""
            SELECT pg_get_serial_sequence(
                'configuracion_calendario_comercial',
                'id_configuracion_calendario_comercial'
            )
        """)
    ).scalar_one()
    before = db_session.execute(
        text(f"SELECT last_value, is_called FROM {sequence_name}")
    ).one()

    _root(db_session, fixture_id=483_000_002)

    after = db_session.execute(
        text(f"SELECT last_value, is_called FROM {sequence_name}")
    ).one()
    assert after == before


@pytest.mark.parametrize("historical_ids", [(483_000_010,), (483_000_010, 483_000_011)])
def test_query_service_usa_unica_raiz_activa_con_historicas(
    db_session, historical_ids
):
    for fixture_id in historical_ids:
        _historical_root(db_session, fixture_id)
    _root(db_session, fixture_id=483_000_012)
    _period(db_session, "2026-01-01", None)

    snapshot = _service(db_session).obtener(date(2026, 2, 1))

    # Las históricas quedaron en versión 2 al aplicar su baja; la activa es v1.
    assert snapshot.version_agregada == 1


def test_query_service_rechaza_si_solo_hay_raiz_historica(db_session):
    _historical_root(db_session, 483_000_020)
    _period(db_session, "2026-01-01", None)

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(date(2026, 2, 1))


def test_query_service_rechaza_multiples_raices_activas_corruptas(db_session):
    # La corrupción se limita a la transacción descartable del test; el índice
    # contractual permanece intacto fuera del rollback del fixture PostgreSQL.
    db_session.execute(
        text("DROP INDEX ux_configuracion_calendario_comercial_activa")
    )
    _root(db_session, fixture_id=483_000_030)
    _root(db_session, fixture_id=483_000_031)
    _period(db_session, "2026-01-01", None)

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(date(2026, 2, 1))


def test_query_service_sin_bootstrap_es_incompleto_y_no_escribe(db_session):
    before = db_session.execute(
        text("""
            SELECT
              (SELECT count(*) FROM valor_parametro),
              (SELECT count(*) FROM configuracion_calendario_comercial),
              (SELECT count(*) FROM operacion_idempotente),
              (SELECT count(*) FROM outbox_event)
        """)
    ).one()
    with pytest.raises(ConfiguracionCalendarioComercialIncompleta):
        _service(db_session).obtener(date(2026, 1, 1))
    after = db_session.execute(
        text("""
            SELECT
              (SELECT count(*) FROM valor_parametro),
              (SELECT count(*) FROM configuracion_calendario_comercial),
              (SELECT count(*) FROM operacion_idempotente),
              (SELECT count(*) FROM outbox_event)
        """)
    ).one()
    assert after == before


def test_query_service_antes_de_primera_vigencia_es_incompleto(db_session):
    _root(db_session)
    _period(db_session, "2026-02-01", None)
    with pytest.raises(ConfiguracionCalendarioComercialIncompleta):
        _service(db_session).obtener(date(2026, 1, 31))


@pytest.mark.parametrize("fecha_efectiva", [date(2026, 2, 1), date(2026, 11, 1)])
def test_query_service_rechaza_historia_con_overlap_global(
    db_session, fecha_efectiva
):
    _root(db_session)
    _period(db_session, "2026-01-01", "2026-06-01", 8, 18)
    _period(db_session, "2026-05-01", "2026-12-01", 12, 22)

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(fecha_efectiva)


def test_query_service_acepta_intervalos_adyacentes(db_session):
    _root(db_session)
    _period(db_session, "2026-01-01", "2026-03-01", 8, 18)
    _period(db_session, "2026-03-01", None, 12, 22)

    snapshot = _service(db_session).obtener(date(2026, 3, 1))

    assert snapshot.dia_cierre_comercial == 12
    assert snapshot.fecha_desde == datetime(2026, 3, 1)
    assert snapshot.fecha_hasta is None


def test_query_service_rechaza_intervalo_abierto_no_final(db_session):
    _root(db_session)
    _period(db_session, "2026-01-01", None, 8, 18)
    _period(db_session, "2026-03-01", None, 12, 22)

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(date(2026, 2, 1))


@pytest.mark.parametrize(
    "corrupt",
    [
        "definicion_faltante",
        "definicion_incompatible",
        "raiz_faltante",
        "solo_un_valor",
        "intervalos_divergentes",
        "duplicidad_aplicable",
    ],
)
def test_query_service_diferencia_inconsistencias_tecnicas(db_session, corrupt):
    if corrupt == "definicion_faltante":
        db_session.execute(
            text("DELETE FROM parametro_sistema WHERE codigo_parametro=:code"),
            {"code": CIERRE},
        )
    elif corrupt == "definicion_incompatible":
        db_session.execute(
            text("""
                UPDATE parametro_sistema SET editable_administrativamente=false
                 WHERE codigo_parametro=:code
            """),
            {"code": CIERRE},
        )
    elif corrupt == "raiz_faltante":
        _period(db_session, "2026-01-01", None)
    else:
        _root(db_session)
        if corrupt == "solo_un_valor":
            _value(db_session, CIERRE, "10", "2026-01-01", None)
        elif corrupt == "intervalos_divergentes":
            _value(db_session, CIERRE, "10", "2026-01-01", None)
            _value(db_session, VENCIMIENTO, "20", "2026-02-01", None)
        else:
            _period(db_session, "2026-01-01", None)
            _value(db_session, CIERRE, "11", "2026-01-01", None)

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(date(2026, 2, 1))


def test_endpoint_requiere_bearer(client):
    response = client.get(ENDPOINT, params={"fecha_efectiva": "2026-01-01"})
    assert response.status_code == 401
    assert response.json()["error_code"] == "INVALID_SESSION"


def test_endpoint_rechaza_bearer_invalido(client):
    response = client.get(
        ENDPOINT,
        params={"fecha_efectiva": "2026-01-01"},
        headers={"Authorization": "Bearer token-invalido"},
    )
    assert response.status_code == 401
    assert response.json()["error_code"] == "INVALID_SESSION"


def test_endpoint_deniega_sin_permiso(client):
    client.app.dependency_overrides[get_authenticated_principal] = _principal
    with patch(
        "app.api.administrative_authorization.AdministrativeAuthorizationService.authorize",
        return_value=AdministrativeAuthorizationDecision.DENIED,
    ):
        response = client.get(ENDPOINT, params={"fecha_efectiva": "2026-01-01"})
    assert response.status_code == 403
    assert response.json()["error_code"] == "autorizacion_insuficiente"


def test_openapi_declara_fecha_efectiva_requerida_y_no_nullable(client):
    operation = client.get("/openapi.json").json()["paths"][ENDPOINT]["get"]
    parameter = next(
        item for item in operation["parameters"] if item["name"] == "fecha_efectiva"
    )
    assert parameter["in"] == "query"
    assert parameter["required"] is True
    assert parameter["schema"]["type"] == "string"
    assert "nullable" not in parameter["schema"]
    assert "anyOf" not in parameter["schema"]


@pytest.mark.parametrize(
    "params",
    [
        {},
        {"fecha_efectiva": "20260101"},
        {"fecha_efectiva": "2026-W01-1"},
        {"fecha_efectiva": "01-01-2026"},
        {"fecha_efectiva": "2026/01/01"},
        {"fecha_efectiva": "2026-1-1"},
        {"fecha_efectiva": "2026-01-1"},
        {"fecha_efectiva": "2026-1-01"},
        {"fecha_efectiva": "no-es-fecha"},
        {"fecha_efectiva": ""},
        {"fecha_efectiva": "2026-02-30"},
        {"fecha_efectiva": "2026-13-01"},
    ],
)
def test_endpoint_valida_fecha_efectiva_explicita(client, params):
    with _grant(client):
        response = client.get(ENDPOINT, params=params)
    assert response.status_code == 422
    assert response.json()["error_code"] == "VALIDATION_ERROR"


@pytest.mark.parametrize("fecha_efectiva", ["2026-01-01", "2026-12-31"])
def test_endpoint_acepta_formato_fecha_efectiva_contractual(client, fecha_efectiva):
    with _grant(client):
        response = client.get(ENDPOINT, params={"fecha_efectiva": fecha_efectiva})
    assert response.status_code == 200
    assert response.json() == {"ok": True, "data": {"estado": "INCOMPLETA"}}


def test_endpoint_permission_based_sin_headers_write_y_x_usuario_no_participa(
    client, db_session
):
    _root(db_session)
    _period(db_session, "2026-01-01", None, 7, 17)
    with _grant(client):
        response = client.get(
            ENDPOINT,
            params={"fecha_efectiva": "2026-05-10"},
            headers={"X-Usuario-Id": "no-se-parsea"},
        )
    assert response.status_code == 200
    assert response.headers["cache-control"] == "no-store"
    assert response.json() == {
        "ok": True,
        "data": {
            "estado": "COMPLETA",
            "dia_cierre_comercial": 7,
            "dia_vencimiento_predeterminado_cuotas": 17,
            "version_agregada": 1,
            "fecha_desde": "2026-01-01T00:00:00",
            "fecha_hasta": None,
        },
    }


def test_endpoint_incompleto_y_error_tecnico_sanitizado(client, db_session):
    with _grant(client):
        incomplete = client.get(ENDPOINT, params={"fecha_efectiva": "2026-01-01"})
    assert incomplete.status_code == 200
    assert incomplete.json() == {"ok": True, "data": {"estado": "INCOMPLETA"}}

    _root(db_session)
    _value(db_session, CIERRE, "10", "2026-01-01", None)
    with _grant(client):
        inconsistent = client.get(
            ENDPOINT, params={"fecha_efectiva": "2026-01-01"}
        )
    assert inconsistent.status_code == 500
    body = inconsistent.json()
    assert body["error_code"] == "CONFIGURACION_CALENDARIO_COMERCIAL_INCONSISTENTE"
    assert body["details"] == {}
    assert "valor_parametro" not in str(body)


@pytest.mark.parametrize("raw", ["32", "1.5"])
def test_valor_corrupto_representable_en_postgresql_es_error_tecnico(
    db_session, raw
):
    _root(db_session)
    # Simula corrupción física externa que PostgreSQL puede representar. La
    # consulta debe defenderse aun si el trigger contractual fue eludido.
    db_session.execute(
        text("ALTER TABLE valor_parametro DISABLE TRIGGER USER")
    )
    try:
        _value(db_session, CIERRE, raw, "2026-01-01", None)
        _value(db_session, VENCIMIENTO, "20", "2026-01-01", None)
    finally:
        db_session.execute(text("ALTER TABLE valor_parametro ENABLE TRIGGER USER"))

    with pytest.raises(ConfiguracionCalendarioComercialInconsistente):
        _service(db_session).obtener(date(2026, 1, 1))
