-- Patch idempotente: egreso_impuesto_empresa V1.
-- Registra pagos/egresos de la empresa por comprobante_impuesto mediante tesoreria.

CREATE TABLE IF NOT EXISTS public.egreso_impuesto_empresa (
    id_egreso_impuesto_empresa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    version_registro integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_comprobante_impuesto bigint NOT NULL,
    id_movimiento_tesoreria bigint NOT NULL,
    fecha_pago date NOT NULL,
    importe_pagado numeric(14,2) NOT NULL,
    medio_pago character varying(50),
    referencia_comprobante character varying(100),
    estado_egreso character varying(30) NOT NULL DEFAULT 'REGISTRADO',
    observaciones text
);

ALTER TABLE public.egreso_impuesto_empresa
    ADD COLUMN IF NOT EXISTS uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    ADD COLUMN IF NOT EXISTS version_registro integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS deleted_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS id_instalacion_origen bigint,
    ADD COLUMN IF NOT EXISTS id_instalacion_ultima_modificacion bigint,
    ADD COLUMN IF NOT EXISTS op_id_alta uuid,
    ADD COLUMN IF NOT EXISTS op_id_ultima_modificacion uuid,
    ADD COLUMN IF NOT EXISTS id_comprobante_impuesto bigint,
    ADD COLUMN IF NOT EXISTS id_movimiento_tesoreria bigint,
    ADD COLUMN IF NOT EXISTS fecha_pago date,
    ADD COLUMN IF NOT EXISTS importe_pagado numeric(14,2),
    ADD COLUMN IF NOT EXISTS medio_pago character varying(50),
    ADD COLUMN IF NOT EXISTS referencia_comprobante character varying(100),
    ADD COLUMN IF NOT EXISTS estado_egreso character varying(30) NOT NULL DEFAULT 'REGISTRADO',
    ADD COLUMN IF NOT EXISTS observaciones text;

UPDATE public.egreso_impuesto_empresa
SET uid_global = gen_random_uuid()
WHERE uid_global IS NULL;

UPDATE public.egreso_impuesto_empresa
SET version_registro = 1
WHERE version_registro IS NULL;

UPDATE public.egreso_impuesto_empresa
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

UPDATE public.egreso_impuesto_empresa
SET updated_at = CURRENT_TIMESTAMP
WHERE updated_at IS NULL;

UPDATE public.egreso_impuesto_empresa
SET estado_egreso = 'REGISTRADO'
WHERE estado_egreso IS NULL;

ALTER TABLE public.egreso_impuesto_empresa
    ALTER COLUMN uid_global SET NOT NULL,
    ALTER COLUMN uid_global SET DEFAULT gen_random_uuid(),
    ALTER COLUMN version_registro SET NOT NULL,
    ALTER COLUMN version_registro SET DEFAULT 1,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN id_comprobante_impuesto SET NOT NULL,
    ALTER COLUMN id_movimiento_tesoreria SET NOT NULL,
    ALTER COLUMN fecha_pago SET NOT NULL,
    ALTER COLUMN importe_pagado SET NOT NULL,
    ALTER COLUMN estado_egreso SET NOT NULL,
    ALTER COLUMN estado_egreso SET DEFAULT 'REGISTRADO';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_eie_importe'
          AND conrelid = 'public.egreso_impuesto_empresa'::regclass
    ) THEN
        ALTER TABLE public.egreso_impuesto_empresa
            ADD CONSTRAINT chk_eie_importe CHECK (importe_pagado > 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_eie_estado'
          AND conrelid = 'public.egreso_impuesto_empresa'::regclass
    ) THEN
        ALTER TABLE public.egreso_impuesto_empresa
            ADD CONSTRAINT chk_eie_estado
            CHECK (estado_egreso IN ('REGISTRADO', 'ANULADO'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_eie_comprobante_impuesto'
          AND conrelid = 'public.egreso_impuesto_empresa'::regclass
    ) THEN
        ALTER TABLE public.egreso_impuesto_empresa
            ADD CONSTRAINT fk_eie_comprobante_impuesto
            FOREIGN KEY (id_comprobante_impuesto)
            REFERENCES public.comprobante_impuesto(id_comprobante_impuesto)
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_eie_movimiento_tesoreria'
          AND conrelid = 'public.egreso_impuesto_empresa'::regclass
    ) THEN
        ALTER TABLE public.egreso_impuesto_empresa
            ADD CONSTRAINT fk_eie_movimiento_tesoreria
            FOREIGN KEY (id_movimiento_tesoreria)
            REFERENCES public.movimiento_tesoreria(id_movimiento_tesoreria)
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_eie_comprobante_impuesto
    ON public.egreso_impuesto_empresa USING btree (id_comprobante_impuesto);

CREATE INDEX IF NOT EXISTS idx_eie_movimiento_tesoreria
    ON public.egreso_impuesto_empresa USING btree (id_movimiento_tesoreria);

CREATE INDEX IF NOT EXISTS idx_eie_uid_global
    ON public.egreso_impuesto_empresa USING btree (uid_global);

CREATE UNIQUE INDEX IF NOT EXISTS ux_eie_op_id_alta_activo
    ON public.egreso_impuesto_empresa USING btree (op_id_alta)
    WHERE ((op_id_alta IS NOT NULL) AND (deleted_at IS NULL));

DROP TRIGGER IF EXISTS trg_bi_eie_core_ef ON public.egreso_impuesto_empresa;
CREATE TRIGGER trg_bi_eie_core_ef
    BEFORE INSERT ON public.egreso_impuesto_empresa
    FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();

DROP TRIGGER IF EXISTS trg_bu_eie_core_ef ON public.egreso_impuesto_empresa;
CREATE TRIGGER trg_bu_eie_core_ef
    BEFORE UPDATE ON public.egreso_impuesto_empresa
    FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();
