BEGIN;

DO $$
BEGIN
    IF to_regclass('public.usuario') IS NULL
       OR to_regclass('public.sucursal') IS NULL
       OR to_regclass('public.instalacion') IS NULL THEN
        RAISE EXCEPTION 'operacion_idempotente requiere public.usuario, public.sucursal y public.instalacion';
    END IF;

    IF to_regclass('public.operacion_idempotente') IS NULL THEN
        CREATE TABLE public.operacion_idempotente (
            id_operacion_idempotente bigint GENERATED BY DEFAULT AS IDENTITY,
            op_id uuid NOT NULL,
            command_code varchar(100) NOT NULL,
            target_type varchar(100) NOT NULL,
            target_uid uuid NULL,
            target_key varchar(200) NULL,
            payload_hash character(64) NOT NULL,
            canonicalization_version integer NOT NULL,
            result_code varchar(100) NOT NULL,
            result_http_status integer NULL,
            result_target_uid uuid NULL,
            result_version integer NULL,
            response_snapshot jsonb NOT NULL,
            id_usuario bigint NULL,
            id_sucursal bigint NULL,
            id_instalacion bigint NOT NULL,
            created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT operacion_idempotente_pkey PRIMARY KEY (id_operacion_idempotente),
            CONSTRAINT uq_operacion_idempotente_op_id UNIQUE (op_id),
            CONSTRAINT chk_operacion_idempotente_command_code CHECK (btrim(command_code) <> ''),
            CONSTRAINT chk_operacion_idempotente_target_type CHECK (btrim(target_type) <> ''),
            CONSTRAINT chk_operacion_idempotente_target_key CHECK (target_key IS NULL OR btrim(target_key) <> ''),
            CONSTRAINT chk_operacion_idempotente_payload_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT chk_operacion_idempotente_canonicalization_version CHECK (canonicalization_version >= 1),
            CONSTRAINT chk_operacion_idempotente_result_code CHECK (btrim(result_code) <> ''),
            CONSTRAINT chk_operacion_idempotente_result_http_status CHECK (result_http_status IS NULL OR result_http_status BETWEEN 100 AND 599),
            CONSTRAINT chk_operacion_idempotente_result_version CHECK (result_version IS NULL OR result_version >= 1),
            CONSTRAINT fk_operacion_idempotente_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE RESTRICT,
            CONSTRAINT fk_operacion_idempotente_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
            CONSTRAINT fk_operacion_idempotente_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
        );
    END IF;
END $$;

DO $$
BEGIN
    IF to_regprocedure('public.fn_assert_instalacion_pertenece_a_sucursal(bigint,bigint,text)') IS NULL THEN
        RAISE EXCEPTION 'operacion_idempotente requiere public.fn_assert_instalacion_pertenece_a_sucursal(bigint,bigint,text)';
    END IF;

    IF to_regprocedure('public.trg_operacion_idempotente_inmutable()') IS NULL THEN
        EXECUTE $function$
            CREATE FUNCTION public.trg_operacion_idempotente_inmutable()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $body$
            BEGIN
                RAISE EXCEPTION 'operacion_idempotente es inmutable: % no permitido', TG_OP;
            END
            $body$
        $function$;
    END IF;

    IF to_regprocedure('public.trg_operacion_idempotente_instalacion_sucursal()') IS NULL THEN
        EXECUTE $function$
            CREATE FUNCTION public.trg_operacion_idempotente_instalacion_sucursal()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $body$
            BEGIN
                PERFORM public.fn_assert_instalacion_pertenece_a_sucursal(
                    NEW.id_instalacion,
                    NEW.id_sucursal,
                    'operacion_idempotente'
                );
                RETURN NEW;
            END
            $body$
        $function$;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'public.operacion_idempotente'::regclass
          AND tgname = 'trg_bi_operacion_idempotente_instalacion_sucursal'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_bi_operacion_idempotente_instalacion_sucursal
        BEFORE INSERT ON public.operacion_idempotente
        FOR EACH ROW EXECUTE FUNCTION public.trg_operacion_idempotente_instalacion_sucursal();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'public.operacion_idempotente'::regclass
          AND tgname = 'trg_bud_operacion_idempotente_inmutable'
          AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER trg_bud_operacion_idempotente_inmutable
        BEFORE UPDATE OR DELETE ON public.operacion_idempotente
        FOR EACH ROW EXECUTE FUNCTION public.trg_operacion_idempotente_inmutable();
    END IF;
END $$;

DO $$
DECLARE
    actual_count integer;
    expected_count constant integer := 17;
    bad text;
BEGIN
    SELECT count(*) INTO actual_count FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'operacion_idempotente';
    IF actual_count <> expected_count THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: se esperaban % columnas y existen %', expected_count, actual_count;
    END IF;

    WITH expected(name, data_type, max_length, nullable, default_expr, identity_generation) AS (VALUES
      ('id_operacion_idempotente','bigint',NULL::integer,'NO',NULL::text,'BY DEFAULT'),
      ('op_id','uuid',NULL,'NO',NULL,NULL), ('command_code','character varying',100,'NO',NULL,NULL),
      ('target_type','character varying',100,'NO',NULL,NULL), ('target_uid','uuid',NULL,'YES',NULL,NULL),
      ('target_key','character varying',200,'YES',NULL,NULL), ('payload_hash','character',64,'NO',NULL,NULL),
      ('canonicalization_version','integer',NULL,'NO',NULL,NULL), ('result_code','character varying',100,'NO',NULL,NULL),
      ('result_http_status','integer',NULL,'YES',NULL,NULL), ('result_target_uid','uuid',NULL,'YES',NULL,NULL),
      ('result_version','integer',NULL,'YES',NULL,NULL), ('response_snapshot','jsonb',NULL,'NO',NULL,NULL),
      ('id_usuario','bigint',NULL,'YES',NULL,NULL), ('id_sucursal','bigint',NULL,'YES',NULL,NULL),
      ('id_instalacion','bigint',NULL,'NO',NULL,NULL),
      ('created_at','timestamp without time zone',NULL,'NO','CURRENT_TIMESTAMP',NULL)
    )
    SELECT e.name INTO bad FROM expected e
    LEFT JOIN information_schema.columns c ON c.table_schema='public'
      AND c.table_name='operacion_idempotente' AND c.column_name=e.name
    WHERE c.column_name IS NULL OR c.data_type<>e.data_type
       OR c.character_maximum_length IS DISTINCT FROM e.max_length
       OR c.is_nullable<>e.nullable
       OR c.column_default IS DISTINCT FROM e.default_expr
       OR c.identity_generation IS DISTINCT FROM e.identity_generation
    LIMIT 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: definición de columna %', bad;
    END IF;

    WITH expected(name, definition) AS (VALUES
      ('operacion_idempotente_pkey','PRIMARY KEY (id_operacion_idempotente)'),
      ('uq_operacion_idempotente_op_id','UNIQUE (op_id)'),
      ('chk_operacion_idempotente_command_code',$def$CHECK ((btrim((command_code)::text) <> ''::text))$def$),
      ('chk_operacion_idempotente_target_type',$def$CHECK ((btrim((target_type)::text) <> ''::text))$def$),
      ('chk_operacion_idempotente_target_key',$def$CHECK (((target_key IS NULL) OR (btrim((target_key)::text) <> ''::text)))$def$),
      ('chk_operacion_idempotente_payload_hash',$def$CHECK ((payload_hash ~ '^[0-9a-f]{64}$'::text))$def$),
      ('chk_operacion_idempotente_canonicalization_version','CHECK ((canonicalization_version >= 1))'),
      ('chk_operacion_idempotente_result_code',$def$CHECK ((btrim((result_code)::text) <> ''::text))$def$),
      ('chk_operacion_idempotente_result_http_status','CHECK (((result_http_status IS NULL) OR ((result_http_status >= 100) AND (result_http_status <= 599))))'),
      ('chk_operacion_idempotente_result_version','CHECK (((result_version IS NULL) OR (result_version >= 1)))'),
      ('fk_operacion_idempotente_usuario','FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE RESTRICT'),
      ('fk_operacion_idempotente_sucursal','FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT'),
      ('fk_operacion_idempotente_instalacion','FOREIGN KEY (id_instalacion) REFERENCES instalacion(id_instalacion) ON DELETE RESTRICT')
    ), actual AS (
      SELECT conname name, pg_get_constraintdef(oid) definition FROM pg_constraint
       WHERE conrelid='public.operacion_idempotente'::regclass
    )
    SELECT coalesce(e.name,a.name) INTO bad FROM expected e FULL JOIN actual a USING (name)
     WHERE e.name IS NULL OR a.name IS NULL OR e.definition<>a.definition LIMIT 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: constraint %', bad;
    END IF;

    IF (SELECT count(*) FROM pg_index WHERE indrelid='public.operacion_idempotente'::regclass) <> 2 THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: índices adicionales o faltantes';
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='fn_assert_instalacion_pertenece_a_sucursal'
         AND p.proargtypes='20 20 25'::oidvector AND p.prorettype='void'::regtype
         AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$DECLARE
    v_ok BOOLEAN;
BEGIN
    IF p_id_instalacion IS NULL OR p_id_sucursal IS NULL THEN
        RETURN;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM instalacion i
        WHERE i.id_instalacion = p_id_instalacion
          AND i.id_sucursal = p_id_sucursal
    ) INTO v_ok;

    IF NOT v_ok THEN
        RAISE EXCEPTION 'Inconsistencia sucursal/instalacion en %: instalacion % no pertenece a sucursal %',
            p_contexto, p_id_instalacion, p_id_sucursal;
    END IF;
END;$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: helper contractual sucursal/instalación'; END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='trg_operacion_idempotente_inmutable'
         AND p.pronargs=0 AND p.prorettype='trigger'::regtype AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$BEGIN
                RAISE EXCEPTION 'operacion_idempotente es inmutable: % no permitido', TG_OP;
            END$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: función de inmutabilidad'; END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='trg_operacion_idempotente_instalacion_sucursal'
         AND p.pronargs=0 AND p.prorettype='trigger'::regtype AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$BEGIN
                PERFORM public.fn_assert_instalacion_pertenece_a_sucursal(
                    NEW.id_instalacion,
                    NEW.id_sucursal,
                    'operacion_idempotente'
                );
                RETURN NEW;
            END$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: función de validación sucursal/instalación'; END IF;

    IF (SELECT count(*) FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass AND NOT tgisinternal) <> 2
       OR NOT EXISTS (
         SELECT 1 FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass
          AND tgname='trg_bud_operacion_idempotente_inmutable' AND NOT tgisinternal
          AND pg_get_triggerdef(oid) = 'CREATE TRIGGER trg_bud_operacion_idempotente_inmutable BEFORE DELETE OR UPDATE ON public.operacion_idempotente FOR EACH ROW EXECUTE FUNCTION trg_operacion_idempotente_inmutable()'
       )
       OR NOT EXISTS (
         SELECT 1 FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass
          AND tgname='trg_bi_operacion_idempotente_instalacion_sucursal' AND NOT tgisinternal
          AND pg_get_triggerdef(oid) = 'CREATE TRIGGER trg_bi_operacion_idempotente_instalacion_sucursal BEFORE INSERT ON public.operacion_idempotente FOR EACH ROW EXECUTE FUNCTION trg_operacion_idempotente_instalacion_sucursal()'
       ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: triggers contractuales'; END IF;
END $$;

COMMIT;
