BEGIN;

CREATE TABLE IF NOT EXISTS public.liquidacion_recupero (
    id_liquidacion_recupero bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    version_registro integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    codigo_liquidacion_recupero character varying(50),
    fecha_liquidacion date NOT NULL,
    fecha_vencimiento date NOT NULL,
    estado_liquidacion character varying(30) NOT NULL DEFAULT 'EMITIDA',
    importe_total_egresado_base numeric(14,2) NOT NULL,
    importe_total_recuperar numeric(14,2) NOT NULL,
    importe_absorbido_empresa numeric(14,2) NOT NULL DEFAULT 0,
    id_relacion_generadora bigint,
    id_obligacion_financiera bigint,
    observaciones text,
    CONSTRAINT chk_lr_estado CHECK (estado_liquidacion IN ('EMITIDA', 'ANULADA')),
    CONSTRAINT chk_lr_fechas CHECK (fecha_vencimiento >= fecha_liquidacion),
    CONSTRAINT chk_lr_importes CHECK (
        importe_total_egresado_base > 0
        AND importe_total_recuperar > 0
        AND importe_absorbido_empresa >= 0
        AND importe_total_recuperar <= importe_total_egresado_base
    ),
    CONSTRAINT fk_lr_relacion_generadora FOREIGN KEY (id_relacion_generadora)
        REFERENCES public.relacion_generadora(id_relacion_generadora) ON DELETE RESTRICT,
    CONSTRAINT fk_lr_obligacion_financiera FOREIGN KEY (id_obligacion_financiera)
        REFERENCES public.obligacion_financiera(id_obligacion_financiera) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.liquidacion_recupero_factura (
    id_liquidacion_recupero_factura bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion_recupero bigint NOT NULL,
    id_factura_servicio bigint NOT NULL,
    importe_egresado_base numeric(14,2) NOT NULL,
    importe_recuperar numeric(14,2) NOT NULL,
    CONSTRAINT chk_lrf_importes CHECK (
        importe_egresado_base > 0
        AND importe_recuperar > 0
        AND importe_recuperar <= importe_egresado_base
    ),
    CONSTRAINT fk_lrf_liquidacion FOREIGN KEY (id_liquidacion_recupero)
        REFERENCES public.liquidacion_recupero(id_liquidacion_recupero) ON DELETE RESTRICT,
    CONSTRAINT fk_lrf_factura_servicio FOREIGN KEY (id_factura_servicio)
        REFERENCES public.factura_servicio(id_factura_servicio) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.liquidacion_recupero_egreso (
    id_liquidacion_recupero_egreso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion_recupero bigint NOT NULL,
    id_egreso_proveedor_factura_servicio bigint NOT NULL,
    importe_imputado_base numeric(14,2) NOT NULL,
    CONSTRAINT chk_lre_importe CHECK (importe_imputado_base > 0),
    CONSTRAINT fk_lre_liquidacion FOREIGN KEY (id_liquidacion_recupero)
        REFERENCES public.liquidacion_recupero(id_liquidacion_recupero) ON DELETE RESTRICT,
    CONSTRAINT fk_lre_egreso FOREIGN KEY (id_egreso_proveedor_factura_servicio)
        REFERENCES public.egreso_proveedor_factura_servicio(id_egreso_proveedor_factura_servicio) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.liquidacion_recupero_responsable (
    id_liquidacion_recupero_responsable bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion_recupero bigint NOT NULL,
    id_persona bigint NOT NULL,
    porcentaje_responsabilidad numeric(5,2) NOT NULL,
    importe_responsable numeric(14,2) NOT NULL,
    origen_responsable character varying(50) NOT NULL DEFAULT 'MANUAL',
    id_asignacion_servicio_responsable bigint,
    CONSTRAINT chk_lrr_porcentaje CHECK (porcentaje_responsabilidad > 0 AND porcentaje_responsabilidad <= 100),
    CONSTRAINT chk_lrr_importe CHECK (importe_responsable > 0),
    CONSTRAINT chk_lrr_origen CHECK (origen_responsable IN ('MANUAL', 'ASIGNACION_SERVICIO_RESPONSABLE')),
    CONSTRAINT fk_lrr_liquidacion FOREIGN KEY (id_liquidacion_recupero)
        REFERENCES public.liquidacion_recupero(id_liquidacion_recupero) ON DELETE RESTRICT,
    CONSTRAINT fk_lrr_persona FOREIGN KEY (id_persona)
        REFERENCES public.persona(id_persona) ON DELETE RESTRICT,
    CONSTRAINT fk_lrr_asignacion FOREIGN KEY (id_asignacion_servicio_responsable)
        REFERENCES public.asignacion_servicio_responsable(id_asignacion_servicio_responsable) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lr_op_id_alta_activo
    ON public.liquidacion_recupero (op_id_alta)
    WHERE op_id_alta IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_lr_codigo_activo
    ON public.liquidacion_recupero (codigo_liquidacion_recupero)
    WHERE codigo_liquidacion_recupero IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_lr_relacion_generadora
    ON public.liquidacion_recupero (id_relacion_generadora);

CREATE INDEX IF NOT EXISTS idx_lr_obligacion_financiera
    ON public.liquidacion_recupero (id_obligacion_financiera);

CREATE INDEX IF NOT EXISTS idx_lrf_factura_servicio
    ON public.liquidacion_recupero_factura (id_factura_servicio);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lre_egreso_activo
    ON public.liquidacion_recupero_egreso (id_egreso_proveedor_factura_servicio);

CREATE INDEX IF NOT EXISTS idx_lrr_persona
    ON public.liquidacion_recupero_responsable (id_persona);

DROP TRIGGER IF EXISTS trg_bi_lr_core_ef ON public.liquidacion_recupero;
CREATE TRIGGER trg_bi_lr_core_ef
BEFORE INSERT ON public.liquidacion_recupero
FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();

DROP TRIGGER IF EXISTS trg_bu_lr_core_ef ON public.liquidacion_recupero;
CREATE TRIGGER trg_bu_lr_core_ef
BEFORE UPDATE ON public.liquidacion_recupero
FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();

CREATE OR REPLACE FUNCTION public.trg_relacion_generadora_polimorfica() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.tipo_origen NOT IN ('venta', 'contrato_alquiler', 'factura_servicio', 'liquidacion_recupero') THEN
        RAISE EXCEPTION 'tipo_origen no permitido en relacion_generadora: %', NEW.tipo_origen;
    END IF;

    CASE NEW.tipo_origen
        WHEN 'venta' THEN
            IF NOT EXISTS (SELECT 1 FROM venta WHERE id_venta = NEW.id_origen) THEN
                RAISE EXCEPTION 'relacion_generadora referencia venta inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'contrato_alquiler' THEN
            IF NOT EXISTS (SELECT 1 FROM contrato_alquiler WHERE id_contrato_alquiler = NEW.id_origen) THEN
                RAISE EXCEPTION 'relacion_generadora referencia contrato_alquiler inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'factura_servicio' THEN
            IF NOT EXISTS (
                SELECT 1
                FROM factura_servicio
                WHERE id_factura_servicio = NEW.id_origen
                  AND deleted_at IS NULL
            ) THEN
                RAISE EXCEPTION 'relacion_generadora referencia factura_servicio inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'liquidacion_recupero' THEN
            IF NOT EXISTS (
                SELECT 1
                FROM liquidacion_recupero
                WHERE id_liquidacion_recupero = NEW.id_origen
                  AND deleted_at IS NULL
            ) THEN
                RAISE EXCEPTION 'relacion_generadora referencia liquidacion_recupero inexistente: %', NEW.id_origen;
            END IF;
    END CASE;

    RETURN NEW;
END;
$$;

COMMIT;
