-- Patch idempotente: liquidacion_impuesto_trasladado V1 fase 1.

CREATE OR REPLACE FUNCTION public.trg_relacion_generadora_polimorfica() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.tipo_origen NOT IN ('venta', 'contrato_alquiler', 'factura_servicio', 'liquidacion_recupero', 'liquidacion_impuesto_trasladado') THEN
        RAISE EXCEPTION 'tipo_origen no permitido en relacion_generadora: %', NEW.tipo_origen;
    END IF;

    CASE NEW.tipo_origen
        WHEN 'venta' THEN
            IF NOT EXISTS (SELECT 1 FROM venta WHERE id_venta = NEW.id_origen) THEN
                RAISE EXCEPTION 'relacion_generadora referencia venta inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'contrato_alquiler' THEN
            IF NOT EXISTS (SELECT 1 FROM contrato_alquiler WHERE id_contrato_alquiler = NEW.id_origen) THEN
                RAISE EXCEPTION 'relacion_generadora referencia contrato_alquiler inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'factura_servicio' THEN
            IF NOT EXISTS (
                SELECT 1 FROM factura_servicio
                WHERE id_factura_servicio = NEW.id_origen
                  AND deleted_at IS NULL
            ) THEN
                RAISE EXCEPTION 'relacion_generadora referencia factura_servicio inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'liquidacion_recupero' THEN
            IF NOT EXISTS (
                SELECT 1 FROM liquidacion_recupero
                WHERE id_liquidacion_recupero = NEW.id_origen
                  AND deleted_at IS NULL
            ) THEN
                RAISE EXCEPTION 'relacion_generadora referencia liquidacion_recupero inexistente: %', NEW.id_origen;
            END IF;
        WHEN 'liquidacion_impuesto_trasladado' THEN
            IF NOT EXISTS (
                SELECT 1 FROM liquidacion_impuesto_trasladado
                WHERE id_liquidacion_impuesto_trasladado = NEW.id_origen
                  AND deleted_at IS NULL
            ) THEN
                RAISE EXCEPTION 'relacion_generadora referencia liquidacion_impuesto_trasladado inexistente: %', NEW.id_origen;
            END IF;
    END CASE;

    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.liquidacion_impuesto_trasladado (
    id_liquidacion_impuesto_trasladado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    version_registro integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    codigo_liquidacion_impuesto_trasladado character varying(50),
    estado_liquidacion character varying(30) NOT NULL DEFAULT 'EMITIDA',
    modalidad_gestion_impuesto character varying(40) NOT NULL,
    fecha_liquidacion date NOT NULL,
    fecha_vencimiento date NOT NULL,
    importe_total_base numeric(14,2) NOT NULL,
    importe_total_trasladar numeric(14,2) NOT NULL,
    importe_absorbido_empresa numeric(14,2) NOT NULL DEFAULT 0,
    id_relacion_generadora bigint,
    id_obligacion_financiera bigint,
    observaciones text
);

CREATE TABLE IF NOT EXISTS public.liquidacion_impuesto_trasladado_comprobante (
    id_liquidacion_impuesto_trasladado_comprobante bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion_impuesto_trasladado bigint NOT NULL,
    id_comprobante_impuesto bigint NOT NULL,
    organismo character varying(120) NOT NULL,
    tipo_impuesto character varying(80) NOT NULL,
    partida_nomenclatura character varying(120),
    numero_comprobante character varying(100) NOT NULL,
    periodo_desde date,
    periodo_hasta date,
    fecha_vencimiento date NOT NULL,
    importe_comprobante numeric(14,2) NOT NULL,
    importe_base numeric(14,2) NOT NULL,
    importe_trasladar numeric(14,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.liquidacion_impuesto_trasladado_egreso (
    id_liquidacion_impuesto_trasladado_egreso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    version_registro integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_liquidacion_impuesto_trasladado bigint NOT NULL,
    id_egreso_impuesto_empresa bigint NOT NULL,
    importe_imputado_base numeric(14,2) NOT NULL,
    estado_liquidacion_impuesto_egreso character varying(30) NOT NULL DEFAULT 'ACTIVO'
);

CREATE TABLE IF NOT EXISTS public.liquidacion_impuesto_trasladado_responsable (
    id_liquidacion_impuesto_trasladado_responsable bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_liquidacion_impuesto_trasladado bigint NOT NULL,
    id_persona bigint NOT NULL,
    porcentaje_responsabilidad numeric(5,2) NOT NULL,
    importe_responsable numeric(14,2) NOT NULL,
    origen_responsable character varying(50) NOT NULL DEFAULT 'MANUAL'
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lit_estado') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado
            ADD CONSTRAINT chk_lit_estado CHECK (estado_liquidacion IN ('EMITIDA', 'ANULADA'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lit_modalidad') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado
            ADD CONSTRAINT chk_lit_modalidad CHECK (modalidad_gestion_impuesto IN ('DIRECTO_RESPONSABLE', 'EMPRESA_PAGA_Y_RECUPERA'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lit_importes') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado
            ADD CONSTRAINT chk_lit_importes CHECK (importe_total_base >= 0 AND importe_total_trasladar > 0 AND importe_absorbido_empresa >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lit_fechas') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado
            ADD CONSTRAINT chk_lit_fechas CHECK (fecha_vencimiento >= fecha_liquidacion);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_litc_importes') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_comprobante
            ADD CONSTRAINT chk_litc_importes CHECK (importe_comprobante >= 0 AND importe_base >= 0 AND importe_trasladar > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lite_importe') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_egreso
            ADD CONSTRAINT chk_lite_importe CHECK (importe_imputado_base > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_lite_estado') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_egreso
            ADD CONSTRAINT chk_lite_estado CHECK (estado_liquidacion_impuesto_egreso IN ('ACTIVO', 'ANULADO'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_litr_porcentaje') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_responsable
            ADD CONSTRAINT chk_litr_porcentaje CHECK (porcentaje_responsabilidad > 0 AND porcentaje_responsabilidad <= 100);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_litr_importe') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_responsable
            ADD CONSTRAINT chk_litr_importe CHECK (importe_responsable >= 0);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lit_relacion_generadora ON public.liquidacion_impuesto_trasladado USING btree (id_relacion_generadora);
CREATE INDEX IF NOT EXISTS idx_lit_obligacion_financiera ON public.liquidacion_impuesto_trasladado USING btree (id_obligacion_financiera);
CREATE INDEX IF NOT EXISTS idx_litc_comprobante ON public.liquidacion_impuesto_trasladado_comprobante USING btree (id_comprobante_impuesto);
CREATE INDEX IF NOT EXISTS idx_lite_egreso ON public.liquidacion_impuesto_trasladado_egreso USING btree (id_egreso_impuesto_empresa);
CREATE INDEX IF NOT EXISTS idx_litr_persona ON public.liquidacion_impuesto_trasladado_responsable USING btree (id_persona);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lite_egreso_activo
    ON public.liquidacion_impuesto_trasladado_egreso USING btree (id_egreso_impuesto_empresa)
    WHERE ((deleted_at IS NULL) AND ((estado_liquidacion_impuesto_egreso)::text = 'ACTIVO'::text));
CREATE UNIQUE INDEX IF NOT EXISTS ux_lit_codigo_activo
    ON public.liquidacion_impuesto_trasladado USING btree (codigo_liquidacion_impuesto_trasladado)
    WHERE ((codigo_liquidacion_impuesto_trasladado IS NOT NULL) AND (deleted_at IS NULL));
CREATE UNIQUE INDEX IF NOT EXISTS ux_lit_op_id_alta_activo
    ON public.liquidacion_impuesto_trasladado USING btree (op_id_alta)
    WHERE ((op_id_alta IS NOT NULL) AND (deleted_at IS NULL));

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lit_relacion_generadora') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado ADD CONSTRAINT fk_lit_relacion_generadora FOREIGN KEY (id_relacion_generadora) REFERENCES public.relacion_generadora(id_relacion_generadora) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lit_obligacion_financiera') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado ADD CONSTRAINT fk_lit_obligacion_financiera FOREIGN KEY (id_obligacion_financiera) REFERENCES public.obligacion_financiera(id_obligacion_financiera) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_litc_liquidacion') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_comprobante ADD CONSTRAINT fk_litc_liquidacion FOREIGN KEY (id_liquidacion_impuesto_trasladado) REFERENCES public.liquidacion_impuesto_trasladado(id_liquidacion_impuesto_trasladado) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_litc_comprobante') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_comprobante ADD CONSTRAINT fk_litc_comprobante FOREIGN KEY (id_comprobante_impuesto) REFERENCES public.comprobante_impuesto(id_comprobante_impuesto) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lite_liquidacion') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_egreso ADD CONSTRAINT fk_lite_liquidacion FOREIGN KEY (id_liquidacion_impuesto_trasladado) REFERENCES public.liquidacion_impuesto_trasladado(id_liquidacion_impuesto_trasladado) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lite_egreso') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_egreso ADD CONSTRAINT fk_lite_egreso FOREIGN KEY (id_egreso_impuesto_empresa) REFERENCES public.egreso_impuesto_empresa(id_egreso_impuesto_empresa) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_litr_liquidacion') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_responsable ADD CONSTRAINT fk_litr_liquidacion FOREIGN KEY (id_liquidacion_impuesto_trasladado) REFERENCES public.liquidacion_impuesto_trasladado(id_liquidacion_impuesto_trasladado) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_litr_persona') THEN
        ALTER TABLE public.liquidacion_impuesto_trasladado_responsable ADD CONSTRAINT fk_litr_persona FOREIGN KEY (id_persona) REFERENCES public.persona(id_persona) ON DELETE RESTRICT;
    END IF;
END $$;

DROP TRIGGER IF EXISTS trg_bi_lit_core_ef ON public.liquidacion_impuesto_trasladado;
CREATE TRIGGER trg_bi_lit_core_ef BEFORE INSERT ON public.liquidacion_impuesto_trasladado FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();
DROP TRIGGER IF EXISTS trg_bu_lit_core_ef ON public.liquidacion_impuesto_trasladado;
CREATE TRIGGER trg_bu_lit_core_ef BEFORE UPDATE ON public.liquidacion_impuesto_trasladado FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();
DROP TRIGGER IF EXISTS trg_bi_lite_core_ef ON public.liquidacion_impuesto_trasladado_egreso;
CREATE TRIGGER trg_bi_lite_core_ef BEFORE INSERT ON public.liquidacion_impuesto_trasladado_egreso FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();
DROP TRIGGER IF EXISTS trg_bu_lite_core_ef ON public.liquidacion_impuesto_trasladado_egreso;
CREATE TRIGGER trg_bu_lite_core_ef BEFORE UPDATE ON public.liquidacion_impuesto_trasladado_egreso FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();
