-- #253 Operativo: caja operativa base.
-- Modelo auditado: no existe tabla caja/caja_operativa en dump vigente; cuenta_financiera y movimiento_tesoreria pertenecen a tesorería/finanzas y no se reutilizan para caja operativa base.

CREATE TABLE IF NOT EXISTS public.caja_operativa (
    id_caja bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_sucursal bigint NOT NULL,
    id_instalacion bigint NOT NULL,
    codigo_caja character varying(50) NOT NULL,
    nombre_caja character varying(150) NOT NULL,
    tipo_caja character varying(30) NOT NULL DEFAULT 'GENERAL',
    moneda_base character varying(3) NOT NULL DEFAULT 'ARS',
    estado_caja character varying(30) NOT NULL DEFAULT 'ACTIVA',
    permite_efectivo boolean DEFAULT true NOT NULL,
    permite_transferencia boolean DEFAULT false NOT NULL,
    permite_cheque boolean DEFAULT false NOT NULL,
    descripcion text,
    observaciones text,
    CONSTRAINT chk_caja_operativa_deleted_at CHECK (deleted_at IS NULL OR deleted_at >= created_at),
    CONSTRAINT chk_caja_operativa_estado CHECK (estado_caja IN ('ACTIVA', 'INACTIVA', 'DADA_DE_BAJA')),
    CONSTRAINT chk_caja_operativa_tipo CHECK (tipo_caja IN ('GENERAL', 'EFECTIVO', 'TESORERIA', 'ADMINISTRATIVA')),
    CONSTRAINT chk_caja_operativa_moneda CHECK (moneda_base IN ('ARS', 'USD')),
    CONSTRAINT fk_caja_operativa_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_uid_global
    ON public.caja_operativa (uid_global);

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_op_id_alta
    ON public.caja_operativa (op_id_alta)
    WHERE op_id_alta IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_codigo_activa
    ON public.caja_operativa (id_sucursal, id_instalacion, codigo_caja)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_caja_operativa_sucursal_instalacion
    ON public.caja_operativa (id_sucursal, id_instalacion);

CREATE INDEX IF NOT EXISTS ix_caja_operativa_estado
    ON public.caja_operativa (estado_caja);
