BEGIN;

CREATE TABLE IF NOT EXISTS public.egreso_proveedor_factura_servicio (
    id_egreso_proveedor_factura_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
    version_registro integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_factura_servicio bigint NOT NULL,
    id_movimiento_tesoreria bigint NOT NULL,
    fecha_pago date NOT NULL,
    importe_pagado numeric(14,2) NOT NULL,
    medio_pago character varying(50),
    referencia_comprobante character varying(100),
    estado_egreso character varying(30) NOT NULL DEFAULT 'REGISTRADO',
    observaciones text,
    CONSTRAINT chk_epfs_importe CHECK (importe_pagado > 0),
    CONSTRAINT chk_epfs_estado CHECK (estado_egreso IN ('REGISTRADO', 'ANULADO')),
    CONSTRAINT fk_epfs_factura_servicio FOREIGN KEY (id_factura_servicio)
        REFERENCES public.factura_servicio(id_factura_servicio) ON DELETE RESTRICT,
    CONSTRAINT fk_epfs_movimiento_tesoreria FOREIGN KEY (id_movimiento_tesoreria)
        REFERENCES public.movimiento_tesoreria(id_movimiento_tesoreria) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_epfs_op_id_alta_activo
    ON public.egreso_proveedor_factura_servicio (op_id_alta)
    WHERE op_id_alta IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_epfs_factura_servicio
    ON public.egreso_proveedor_factura_servicio (id_factura_servicio);

CREATE INDEX IF NOT EXISTS idx_epfs_movimiento_tesoreria
    ON public.egreso_proveedor_factura_servicio (id_movimiento_tesoreria);

CREATE INDEX IF NOT EXISTS idx_epfs_uid_global
    ON public.egreso_proveedor_factura_servicio (uid_global);

DROP TRIGGER IF EXISTS trg_bi_epfs_core_ef
    ON public.egreso_proveedor_factura_servicio;
CREATE TRIGGER trg_bi_epfs_core_ef
BEFORE INSERT ON public.egreso_proveedor_factura_servicio
FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();

DROP TRIGGER IF EXISTS trg_bu_epfs_core_ef
    ON public.egreso_proveedor_factura_servicio;
CREATE TRIGGER trg_bu_epfs_core_ef
BEFORE UPDATE ON public.egreso_proveedor_factura_servicio
FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();

COMMIT;
