-- #482: estructura inicial del calendario comercial administrativo.
-- No crea valores funcionales, fila raíz, API, outbox, sync ni historial.
BEGIN;

LOCK TABLE public.parametro_sistema, public.valor_parametro, public.permiso,
  public.rol_seguridad, public.rol_seguridad_permiso IN SHARE ROW EXCLUSIVE MODE;

DO $$
DECLARE
  tipo_id bigint; alcance_id bigint; rol_id bigint; permiso_id bigint;
  item record; existentes bigint; parametro_id bigint;
BEGIN
  SELECT count(*), min(id_tipo_dato_parametro) INTO existentes, tipo_id
    FROM public.tipo_dato_parametro WHERE codigo_tipo_dato='ENTERO';
  IF existentes <> 1 THEN RAISE EXCEPTION 'se requiere exactamente un tipo ENTERO'; END IF;
  SELECT count(*), min(id_alcance_parametro) INTO existentes, alcance_id
    FROM public.alcance_parametro WHERE codigo_alcance='GLOBAL';
  IF existentes <> 1 THEN RAISE EXCEPTION 'se requiere exactamente un alcance GLOBAL'; END IF;

  FOR item IN SELECT * FROM (VALUES
    ('DIA_CIERRE_COMERCIAL', 'Día de cierre comercial',
     'Día del mes, entre 1 y 31, utilizado para determinar el período base sugerido de una venta según su fecha de negocio.'),
    ('DIA_VENCIMIENTO_PREDETERMINADO_CUOTAS', 'Día de vencimiento predeterminado de cuotas',
     'Día del mes, entre 1 y 31, utilizado para sugerir el vencimiento de las cuotas; la fecha sugerida puede ser modificada antes de confirmar la venta.')
  ) AS x(codigo, nombre, descripcion)
  LOOP
    SELECT count(*), min(id_parametro_sistema) INTO existentes, parametro_id
      FROM public.parametro_sistema WHERE codigo_parametro=item.codigo;
    IF existentes > 1 THEN RAISE EXCEPTION 'cardinalidad incompatible para %', item.codigo; END IF;
    IF existentes = 1 AND NOT EXISTS (
      SELECT 1 FROM public.parametro_sistema
       WHERE id_parametro_sistema=parametro_id
         AND id_tipo_dato_parametro=tipo_id AND id_alcance_parametro=alcance_id
         AND nombre_parametro=item.nombre AND descripcion=item.descripcion
         AND exponible_api_administrativa AND NOT es_sensible
         AND editable_administrativamente
    ) THEN RAISE EXCEPTION 'definición % preexistente incompatible', item.codigo; END IF;
    IF existentes = 0 THEN
      INSERT INTO public.parametro_sistema(
        id_tipo_dato_parametro,id_alcance_parametro,codigo_parametro,
        nombre_parametro,descripcion,exponible_api_administrativa,es_sensible,
        editable_administrativamente)
      VALUES(tipo_id,alcance_id,item.codigo,item.nombre,item.descripcion,true,false,true);
    END IF;
  END LOOP;

  SELECT count(*), min(id_rol_seguridad) INTO existentes, rol_id
    FROM public.rol_seguridad WHERE codigo_rol='ADMINISTRADOR_SISTEMA';
  IF existentes <> 1 OR NOT EXISTS (SELECT 1 FROM public.rol_seguridad WHERE id_rol_seguridad=rol_id AND estado_rol='ACTIVO')
  THEN RAISE EXCEPTION 'se requiere exactamente un rol ADMINISTRADOR_SISTEMA activo'; END IF;

  SELECT count(*), min(id_permiso) INTO existentes, permiso_id FROM public.permiso
   WHERE codigo_permiso='ADMIN.CONFIG.CALENDARIO_COMERCIAL.ADMINISTRAR';
  IF existentes > 1 THEN RAISE EXCEPTION 'cardinalidad incompatible del permiso calendario comercial'; END IF;
  IF existentes = 1 AND NOT EXISTS (
    SELECT 1 FROM public.permiso WHERE id_permiso=permiso_id
      AND nombre_permiso='Administrar calendario comercial'
      AND descripcion='Permite crear y programar configuraciones del calendario comercial global, incluyendo día de cierre comercial y día de vencimiento predeterminado de cuotas.'
      AND estado_permiso='ACTIVO'
  ) THEN RAISE EXCEPTION 'permiso calendario comercial preexistente incompatible'; END IF;
  IF existentes = 0 THEN
    INSERT INTO public.permiso(codigo_permiso,nombre_permiso,descripcion,estado_permiso)
    VALUES('ADMIN.CONFIG.CALENDARIO_COMERCIAL.ADMINISTRAR','Administrar calendario comercial',
      'Permite crear y programar configuraciones del calendario comercial global, incluyendo día de cierre comercial y día de vencimiento predeterminado de cuotas.','ACTIVO')
    RETURNING id_permiso INTO permiso_id;
  END IF;
  IF (SELECT count(*) FROM public.rol_seguridad_permiso WHERE id_rol_seguridad=rol_id AND id_permiso=permiso_id) > 1
  THEN RAISE EXCEPTION 'vínculo calendario comercial duplicado'; END IF;
  INSERT INTO public.rol_seguridad_permiso(id_rol_seguridad,id_permiso)
  SELECT rol_id,permiso_id WHERE NOT EXISTS (
    SELECT 1 FROM public.rol_seguridad_permiso WHERE id_rol_seguridad=rol_id AND id_permiso=permiso_id);
END $$;

DO $$ BEGIN
  IF to_regclass('public.configuracion_calendario_comercial') IS NULL THEN
    CREATE TABLE public.configuracion_calendario_comercial (
      id_configuracion_calendario_comercial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uid_global uuid NOT NULL DEFAULT gen_random_uuid(),
      version_registro integer NOT NULL DEFAULT 1,
      created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      deleted_at timestamp without time zone,
      id_instalacion_origen bigint,
      id_instalacion_ultima_modificacion bigint,
      op_id_alta uuid,
      op_id_ultima_modificacion uuid,
      CONSTRAINT uq_configuracion_calendario_comercial_uid UNIQUE(uid_global),
      CONSTRAINT chk_configuracion_calendario_comercial_version CHECK(version_registro >= 1),
      CONSTRAINT chk_configuracion_calendario_comercial_deleted CHECK(deleted_at IS NULL OR deleted_at >= created_at),
      CONSTRAINT fk_configuracion_calendario_comercial_instalacion_origen FOREIGN KEY(id_instalacion_origen) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT,
      CONSTRAINT fk_configuracion_calendario_comercial_instalacion_modificacion FOREIGN KEY(id_instalacion_ultima_modificacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
    );
  END IF;
END $$;

DO $$
DECLARE cols bigint; actual text; item record; found_count bigint;
BEGIN
  SELECT count(*) INTO cols FROM information_schema.columns WHERE table_schema='public'
    AND table_name='configuracion_calendario_comercial'
    AND (column_name,data_type,is_nullable) IN (
      ('id_configuracion_calendario_comercial','bigint','NO'),('uid_global','uuid','NO'),
      ('version_registro','integer','NO'),('created_at','timestamp without time zone','NO'),
      ('updated_at','timestamp without time zone','NO'),('deleted_at','timestamp without time zone','YES'),
      ('id_instalacion_origen','bigint','YES'),('id_instalacion_ultima_modificacion','bigint','YES'),
      ('op_id_alta','uuid','YES'),('op_id_ultima_modificacion','uuid','YES'));
  IF cols <> 10 OR (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='configuracion_calendario_comercial') <> 10
  THEN RAISE EXCEPTION 'tabla configuracion_calendario_comercial incompatible'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute WHERE attrelid='public.configuracion_calendario_comercial'::regclass
      AND attname='id_configuracion_calendario_comercial' AND attidentity='d'
  ) THEN RAISE EXCEPTION 'identity de configuracion_calendario_comercial incompatible'; END IF;

  FOR item IN SELECT * FROM (VALUES
    ('uid_global','gen_random_uuid()'), ('version_registro','1'),
    ('created_at','CURRENT_TIMESTAMP'), ('updated_at','CURRENT_TIMESTAMP')
  ) AS x(columna, esperado)
  LOOP
    SELECT pg_get_expr(d.adbin,d.adrelid) INTO actual
      FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
     WHERE a.attrelid='public.configuracion_calendario_comercial'::regclass AND a.attname=item.columna;
    IF (item.columna='uid_global' AND regexp_replace(coalesce(actual,''),'[[:space:]]','','g') <> item.esperado)
       OR (item.columna='version_registro' AND regexp_replace(coalesce(actual,''),'[[:space:]()]|::integer','','g') <> item.esperado)
       OR (item.columna IN ('created_at','updated_at') AND upper(regexp_replace(coalesce(actual,''),'[[:space:]()]','','g')) NOT IN ('CURRENT_TIMESTAMP','NOW'))
    THEN RAISE EXCEPTION 'default de %.% incompatible: %', 'configuracion_calendario_comercial', item.columna, actual; END IF;
  END LOOP;

  FOR item IN SELECT * FROM (VALUES
    ('p','PRIMARYKEY(id_configuracion_calendario_comercial)'),
    ('u','UNIQUE(uid_global)'),
    ('c','CHECK(version_registro>=1)'),
    ('c','CHECK(deleted_atISNULLORdeleted_at>=created_at)'),
    ('f','FOREIGNKEY(id_instalacion_origen)REFERENCESinstalacion(id_instalacion)ONDELETERESTRICT'),
    ('f','FOREIGNKEY(id_instalacion_ultima_modificacion)REFERENCESinstalacion(id_instalacion)ONDELETERESTRICT')
  ) AS x(tipo, esperado)
  LOOP
    SELECT count(*) INTO found_count FROM pg_constraint
     WHERE conrelid='public.configuracion_calendario_comercial'::regclass AND contype=item.tipo
       AND regexp_replace(replace(pg_get_constraintdef(oid),'public.',''),'[[:space:]()]|::[a-z ]+','','g') =
           regexp_replace(item.esperado,'[[:space:]()]|::[a-z ]+','','g');
    IF found_count <> 1 THEN RAISE EXCEPTION 'constraint contractual ausente o incompatible: %', item.esperado; END IF;
  END LOOP;
  SELECT indexdef INTO actual FROM pg_indexes WHERE schemaname='public' AND indexname='ux_configuracion_calendario_comercial_activa';
  IF actual IS NULL THEN
    CREATE UNIQUE INDEX ux_configuracion_calendario_comercial_activa
      ON public.configuracion_calendario_comercial ((true)) WHERE deleted_at IS NULL;
  ELSIF regexp_replace(actual,'[[:space:]()]','','g') <> 'CREATEUNIQUEINDEXux_configuracion_calendario_comercial_activaONpublic.configuracion_calendario_comercialUSINGbtreetrueWHEREdeleted_atISNULL'
  THEN RAISE EXCEPTION 'índice singleton calendario comercial incompatible'; END IF;
  SELECT indexdef INTO actual FROM pg_indexes WHERE schemaname='public' AND indexname='ux_configuracion_calendario_comercial_op_id_alta';
  IF actual IS NULL THEN
    CREATE UNIQUE INDEX ux_configuracion_calendario_comercial_op_id_alta
      ON public.configuracion_calendario_comercial(op_id_alta) WHERE op_id_alta IS NOT NULL;
  ELSIF regexp_replace(actual,'[[:space:]()]','','g') <> 'CREATEUNIQUEINDEXux_configuracion_calendario_comercial_op_id_altaONpublic.configuracion_calendario_comercialUSINGbtreeop_id_altaWHEREop_id_altaISNOTNULL'
  THEN RAISE EXCEPTION 'índice op_id_alta calendario comercial incompatible'; END IF;
END $$;

DO $$ DECLARE definition text; BEGIN
  IF to_regprocedure('public.trg_configuracion_calendario_comercial_core_ef()') IS NOT NULL THEN
    SELECT pg_get_functiondef('public.trg_configuracion_calendario_comercial_core_ef()'::regprocedure) INTO definition;
    definition := regexp_replace(definition,'[[:space:]]','','g');
    IF definition NOT LIKE '%IFTG_OP=''INSERT''THEN%'
       OR definition NOT LIKE '%NEW.version_registro:=OLD.version_registro+1%'
       OR definition NOT LIKE '%NEW.uid_global:=OLD.uid_global%'
    THEN RAISE EXCEPTION 'función CORE-EF calendario comercial incompatible'; END IF;
  ELSE
    EXECUTE $ddl$CREATE FUNCTION public.trg_configuracion_calendario_comercial_core_ef() RETURNS trigger
LANGUAGE plpgsql AS $body$
BEGIN
  IF TG_OP='INSERT' THEN
    IF NEW.version_registro <> 1 THEN RAISE EXCEPTION 'calendario comercial debe iniciar en versión 1'; END IF;
    NEW.op_id_ultima_modificacion := COALESCE(NEW.op_id_ultima_modificacion,NEW.op_id_alta);
    NEW.id_instalacion_ultima_modificacion := COALESCE(NEW.id_instalacion_ultima_modificacion,NEW.id_instalacion_origen);
  ELSE
    NEW.uid_global:=OLD.uid_global; NEW.created_at:=OLD.created_at;
    NEW.id_instalacion_origen:=OLD.id_instalacion_origen; NEW.op_id_alta:=OLD.op_id_alta;
    NEW.updated_at:=CURRENT_TIMESTAMP; NEW.version_registro:=OLD.version_registro+1;
  END IF;
  RETURN NEW;
END $body$;$ddl$;
  END IF;
END $$;

DO $$ DECLARE actual text; BEGIN
  SELECT pg_get_triggerdef(oid) INTO actual FROM pg_trigger
   WHERE tgrelid='public.configuracion_calendario_comercial'::regclass
     AND tgname='trg_biu_configuracion_calendario_comercial_core_ef' AND NOT tgisinternal;
  IF actual IS NULL THEN
    CREATE TRIGGER trg_biu_configuracion_calendario_comercial_core_ef BEFORE INSERT OR UPDATE
      ON public.configuracion_calendario_comercial FOR EACH ROW
      EXECUTE FUNCTION public.trg_configuracion_calendario_comercial_core_ef();
  ELSIF actual NOT LIKE '%BEFORE INSERT OR UPDATE%'
     OR actual NOT LIKE '%FOR EACH ROW%'
     OR actual NOT LIKE '%trg_configuracion_calendario_comercial_core_ef()%'
  THEN RAISE EXCEPTION 'trigger CORE-EF calendario comercial incompatible'; END IF;
END $$;

DO $$ DECLARE definition text; BEGIN
  IF to_regprocedure('public.trg_valor_parametro_calendario_comercial()') IS NOT NULL THEN
    SELECT pg_get_functiondef('public.trg_valor_parametro_calendario_comercial()'::regprocedure) INTO definition;
    definition := regexp_replace(definition,'[[:space:]]','','g');
    IF definition NOT LIKE '%DIA_CIERRE_COMERCIAL%'
       OR definition NOT LIKE '%DIA_VENCIMIENTO_PREDETERMINADO_CUOTAS%'
       OR definition NOT LIKE '%NOTBETWEEN1AND31%'
    THEN RAISE EXCEPTION 'función rango calendario comercial incompatible'; END IF;
  ELSE
    EXECUTE $ddl$CREATE FUNCTION public.trg_valor_parametro_calendario_comercial() RETURNS trigger
LANGUAGE plpgsql AS $body$
DECLARE codigo text;
BEGIN
  SELECT codigo_parametro INTO codigo FROM public.parametro_sistema
   WHERE id_parametro_sistema=NEW.id_parametro_sistema;
  IF codigo IN ('DIA_CIERRE_COMERCIAL','DIA_VENCIMIENTO_PREDETERMINADO_CUOTAS')
     AND (NEW.valor_parametro IS NULL OR NEW.valor_parametro !~ '^[0-9]+$'
          OR length(NEW.valor_parametro)>2 OR NEW.valor_parametro::integer NOT BETWEEN 1 AND 31)
  THEN RAISE EXCEPTION 'valor de calendario comercial debe ser un entero entre 1 y 31'; END IF;
  RETURN NEW;
END $body$;$ddl$;
  END IF;
END $$;

DO $$ DECLARE actual text; BEGIN
  SELECT pg_get_triggerdef(oid) INTO actual FROM pg_trigger WHERE tgrelid='public.valor_parametro'::regclass
   AND tgname='trg_biu_valor_parametro_calendario_comercial' AND NOT tgisinternal;
  IF actual IS NULL THEN
    CREATE TRIGGER trg_biu_valor_parametro_calendario_comercial BEFORE INSERT OR UPDATE
      ON public.valor_parametro FOR EACH ROW EXECUTE FUNCTION public.trg_valor_parametro_calendario_comercial();
  ELSIF actual NOT LIKE '%BEFORE INSERT OR UPDATE%'
     OR actual NOT LIKE '%FOR EACH ROW%'
     OR actual NOT LIKE '%trg_valor_parametro_calendario_comercial()%'
  THEN RAISE EXCEPTION 'trigger rango calendario comercial incompatible'; END IF;
END $$;

COMMIT;
