BEGIN;

DO $$
DECLARE
    helper_body text;
    helper_count integer;
BEGIN
    PERFORM set_config('sistema.patch_operacion_idempotente_created', 'false', true);
    IF to_regclass('public.usuario') IS NULL
       OR to_regclass('public.sucursal') IS NULL
       OR to_regclass('public.instalacion') IS NULL THEN
        RAISE EXCEPTION 'operacion_idempotente requiere public.usuario, public.sucursal y public.instalacion';
    END IF;

    SELECT count(*) INTO helper_count
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid=p.pronamespace
     WHERE n.nspname='public'
       AND p.proname='fn_assert_instalacion_pertenece_a_sucursal';
    IF helper_count <> 1 THEN
        RAISE EXCEPTION 'operacion_idempotente requiere una única función contractual public.fn_assert_instalacion_pertenece_a_sucursal';
    END IF;

    SELECT p.prosrc INTO helper_body
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid=p.pronamespace
     WHERE n.nspname='public'
       AND p.proname='fn_assert_instalacion_pertenece_a_sucursal'
       AND p.proargtypes='20 20 25'::oidvector
       AND p.prorettype='void'::regtype
       AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
       AND p.provolatile='v' AND NOT p.prosecdef AND NOT p.proisstrict;
    IF helper_body IS NULL THEN
        RAISE EXCEPTION 'operacion_idempotente requiere la firma contractual fn_assert_instalacion_pertenece_a_sucursal(bigint,bigint,text)';
    END IF;

    IF regexp_replace(helper_body,'\s','','g') = regexp_replace($safe$DECLARE
    v_ok BOOLEAN;
BEGIN
    IF p_id_instalacion IS NULL OR p_id_sucursal IS NULL THEN
        RETURN;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM public.instalacion AS i
        WHERE i.id_instalacion = p_id_instalacion
          AND i.id_sucursal = p_id_sucursal
    ) INTO v_ok;

    IF NOT v_ok THEN
        RAISE EXCEPTION 'Inconsistencia sucursal/instalacion en %: instalacion % no pertenece a sucursal %',
            p_contexto, p_id_instalacion, p_id_sucursal;
    END IF;
END;$safe$,'\s','','g') THEN
        NULL;
    ELSIF regexp_replace(helper_body,'\s','','g') = regexp_replace($historical$DECLARE
    v_ok BOOLEAN;
BEGIN
    IF p_id_instalacion IS NULL OR p_id_sucursal IS NULL THEN
        RETURN;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM instalacion i
        WHERE i.id_instalacion = p_id_instalacion
          AND i.id_sucursal = p_id_sucursal
    ) INTO v_ok;

    IF NOT v_ok THEN
        RAISE EXCEPTION 'Inconsistencia sucursal/instalacion en %: instalacion % no pertenece a sucursal %',
            p_contexto, p_id_instalacion, p_id_sucursal;
    END IF;
END;$historical$,'\s','','g') THEN
        -- Migración explícita y acotada de la única variante histórica conocida.
        CREATE OR REPLACE FUNCTION public.fn_assert_instalacion_pertenece_a_sucursal(
            p_id_instalacion bigint, p_id_sucursal bigint, p_contexto text
        ) RETURNS void LANGUAGE plpgsql AS $safe_body$
        DECLARE
            v_ok BOOLEAN;
        BEGIN
            IF p_id_instalacion IS NULL OR p_id_sucursal IS NULL THEN
                RETURN;
            END IF;
            SELECT EXISTS (
                SELECT 1 FROM public.instalacion AS i
                WHERE i.id_instalacion = p_id_instalacion
                  AND i.id_sucursal = p_id_sucursal
            ) INTO v_ok;
            IF NOT v_ok THEN
                RAISE EXCEPTION 'Inconsistencia sucursal/instalacion en %: instalacion % no pertenece a sucursal %',
                    p_contexto, p_id_instalacion, p_id_sucursal;
            END IF;
        END;
        $safe_body$;
    ELSE
        RAISE EXCEPTION 'operacion_idempotente incompatible: helper sucursal/instalación desconocido';
    END IF;

    IF to_regclass('public.operacion_idempotente') IS NOT NULL AND NOT EXISTS (
        SELECT 1
          FROM pg_class c
          JOIN pg_namespace n ON n.oid=c.relnamespace
         WHERE n.nspname='public' AND c.relname='operacion_idempotente'
           AND c.oid=to_regclass('public.operacion_idempotente')
           AND c.relkind='r' AND c.relpersistence='p'
    ) THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: debe ser tabla ordinaria permanente/WAL-logged';
    END IF;

    IF to_regclass('public.operacion_idempotente') IS NOT NULL THEN
        LOCK TABLE public.operacion_idempotente IN ACCESS EXCLUSIVE MODE;
    END IF;

    IF to_regclass('public.operacion_idempotente') IS NULL THEN
        CREATE TABLE public.operacion_idempotente (
            id_operacion_idempotente bigint GENERATED BY DEFAULT AS IDENTITY,
            op_id uuid NOT NULL,
            command_code varchar(100) NOT NULL,
            target_type varchar(100) NOT NULL,
            target_uid uuid NULL,
            target_key varchar(200) NULL,
            payload_hash character(64) NOT NULL,
            canonicalization_version integer NOT NULL,
            result_code varchar(100) NOT NULL,
            result_http_status integer NULL,
            result_target_uid uuid NULL,
            result_version integer NULL,
            response_snapshot jsonb NOT NULL,
            id_usuario bigint NULL,
            id_sucursal bigint NULL,
            id_instalacion bigint NOT NULL,
            created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT operacion_idempotente_pkey PRIMARY KEY (id_operacion_idempotente),
            CONSTRAINT uq_operacion_idempotente_op_id UNIQUE (op_id),
            CONSTRAINT chk_operacion_idempotente_command_code CHECK (btrim(command_code, E' \t\n\r\f\x0B') <> ''),
            CONSTRAINT chk_operacion_idempotente_target_type CHECK (btrim(target_type, E' \t\n\r\f\x0B') <> ''),
            CONSTRAINT chk_operacion_idempotente_target_key CHECK (target_key IS NULL OR btrim(target_key, E' \t\n\r\f\x0B') <> ''),
            CONSTRAINT chk_operacion_idempotente_payload_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT chk_operacion_idempotente_canonicalization_version CHECK (canonicalization_version >= 1),
            CONSTRAINT chk_operacion_idempotente_result_code CHECK (btrim(result_code, E' \t\n\r\f\x0B') <> ''),
            CONSTRAINT chk_operacion_idempotente_result_http_status CHECK (result_http_status IS NULL OR result_http_status BETWEEN 100 AND 599),
            CONSTRAINT chk_operacion_idempotente_result_version CHECK (result_version IS NULL OR result_version >= 1),
            CONSTRAINT fk_operacion_idempotente_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE RESTRICT,
            CONSTRAINT fk_operacion_idempotente_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
            CONSTRAINT fk_operacion_idempotente_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
        );
        PERFORM set_config('sistema.patch_operacion_idempotente_created', 'true', true);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regprocedure('public.fn_assert_instalacion_pertenece_a_sucursal(bigint,bigint,text)') IS NULL THEN
        RAISE EXCEPTION 'operacion_idempotente requiere public.fn_assert_instalacion_pertenece_a_sucursal(bigint,bigint,text)';
    END IF;

    IF to_regprocedure('public.trg_operacion_idempotente_inmutable()') IS NULL THEN
        IF current_setting('sistema.patch_operacion_idempotente_created') <> 'true' THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: falta función de inmutabilidad';
        END IF;
        EXECUTE $function$
            CREATE FUNCTION public.trg_operacion_idempotente_inmutable()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $body$
            BEGIN
                RAISE EXCEPTION 'operacion_idempotente es inmutable: % no permitido', TG_OP;
            END
            $body$
        $function$;
    END IF;

    IF to_regprocedure('public.trg_operacion_idempotente_instalacion_sucursal()') IS NULL THEN
        IF current_setting('sistema.patch_operacion_idempotente_created') <> 'true' THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: falta función de validación sucursal/instalación';
        END IF;
        EXECUTE $function$
            CREATE FUNCTION public.trg_operacion_idempotente_instalacion_sucursal()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $body$
            BEGIN
                PERFORM public.fn_assert_instalacion_pertenece_a_sucursal(
                    NEW.id_instalacion,
                    NEW.id_sucursal,
                    'operacion_idempotente'
                );
                RETURN NEW;
            END
            $body$
        $function$;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'public.operacion_idempotente'::regclass
          AND tgname = 'trg_bi_operacion_idempotente_instalacion_sucursal'
          AND NOT tgisinternal
    ) THEN
        IF current_setting('sistema.patch_operacion_idempotente_created') <> 'true' THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: falta trigger de validación sucursal/instalación';
        END IF;
        CREATE TRIGGER trg_bi_operacion_idempotente_instalacion_sucursal
        BEFORE INSERT ON public.operacion_idempotente
        FOR EACH ROW EXECUTE FUNCTION public.trg_operacion_idempotente_instalacion_sucursal();
        ALTER TABLE public.operacion_idempotente
        ENABLE ALWAYS TRIGGER trg_bi_operacion_idempotente_instalacion_sucursal;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'public.operacion_idempotente'::regclass
          AND tgname = 'trg_bud_operacion_idempotente_inmutable'
          AND NOT tgisinternal
    ) THEN
        IF current_setting('sistema.patch_operacion_idempotente_created') <> 'true' THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: falta trigger de inmutabilidad UPDATE/DELETE';
        END IF;
        CREATE TRIGGER trg_bud_operacion_idempotente_inmutable
        BEFORE UPDATE OR DELETE ON public.operacion_idempotente
        FOR EACH ROW EXECUTE FUNCTION public.trg_operacion_idempotente_inmutable();
        ALTER TABLE public.operacion_idempotente
        ENABLE ALWAYS TRIGGER trg_bud_operacion_idempotente_inmutable;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgrelid = 'public.operacion_idempotente'::regclass
          AND tgname = 'trg_bt_operacion_idempotente_inmutable'
          AND NOT tgisinternal
    ) THEN
        IF current_setting('sistema.patch_operacion_idempotente_created') <> 'true' THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: falta trigger de inmutabilidad TRUNCATE';
        END IF;
        CREATE TRIGGER trg_bt_operacion_idempotente_inmutable
        BEFORE TRUNCATE ON public.operacion_idempotente
        FOR EACH STATEMENT EXECUTE FUNCTION public.trg_operacion_idempotente_inmutable();
        ALTER TABLE public.operacion_idempotente
        ENABLE ALWAYS TRIGGER trg_bt_operacion_idempotente_inmutable;
    END IF;
END $$;

DO $$
DECLARE
    actual_count integer;
    expected_count constant integer := 17;
    bad text;
    identity_sequence oid;
    sequence_last_value bigint;
    sequence_is_called boolean;
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_class c
          JOIN pg_namespace n ON n.oid=c.relnamespace
         WHERE n.nspname='public' AND c.relname='operacion_idempotente'
           AND c.oid=to_regclass('public.operacion_idempotente')
           AND c.relkind='r' AND c.relpersistence='p' AND NOT c.relispartition
           AND NOT c.relrowsecurity AND NOT c.relforcerowsecurity
    ) THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: persistencia física no contractual';
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_inherits
         WHERE inhrelid='public.operacion_idempotente'::regclass
            OR inhparent='public.operacion_idempotente'::regclass
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: inheritance/particionamiento no permitido'; END IF;
    IF EXISTS (SELECT 1 FROM pg_rewrite WHERE ev_class='public.operacion_idempotente'::regclass) THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: rules no permitidas';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_policy WHERE polrelid='public.operacion_idempotente'::regclass) THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: policies RLS no permitidas';
    END IF;

    SELECT count(*) INTO actual_count FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'operacion_idempotente';
    IF actual_count <> expected_count THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: se esperaban % columnas y existen %', expected_count, actual_count;
    END IF;

    WITH expected(name, data_type, max_length, nullable, default_expr, identity_generation) AS (VALUES
      ('id_operacion_idempotente','bigint',NULL::integer,'NO',NULL::text,'BY DEFAULT'),
      ('op_id','uuid',NULL,'NO',NULL,NULL), ('command_code','character varying',100,'NO',NULL,NULL),
      ('target_type','character varying',100,'NO',NULL,NULL), ('target_uid','uuid',NULL,'YES',NULL,NULL),
      ('target_key','character varying',200,'YES',NULL,NULL), ('payload_hash','character',64,'NO',NULL,NULL),
      ('canonicalization_version','integer',NULL,'NO',NULL,NULL), ('result_code','character varying',100,'NO',NULL,NULL),
      ('result_http_status','integer',NULL,'YES',NULL,NULL), ('result_target_uid','uuid',NULL,'YES',NULL,NULL),
      ('result_version','integer',NULL,'YES',NULL,NULL), ('response_snapshot','jsonb',NULL,'NO',NULL,NULL),
      ('id_usuario','bigint',NULL,'YES',NULL,NULL), ('id_sucursal','bigint',NULL,'YES',NULL,NULL),
      ('id_instalacion','bigint',NULL,'NO',NULL,NULL),
      ('created_at','timestamp without time zone',NULL,'NO','CURRENT_TIMESTAMP',NULL)
    )
    SELECT e.name INTO bad FROM expected e
    LEFT JOIN information_schema.columns c ON c.table_schema='public'
      AND c.table_name='operacion_idempotente' AND c.column_name=e.name
    WHERE c.column_name IS NULL OR c.data_type<>e.data_type
       OR c.character_maximum_length IS DISTINCT FROM e.max_length
       OR c.is_nullable<>e.nullable
       OR c.column_default IS DISTINCT FROM e.default_expr
       OR c.identity_generation IS DISTINCT FROM e.identity_generation
    LIMIT 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: definición de columna %', bad;
    END IF;

    WITH expected(attnum, name, type_oid, typmod, not_null, identity_kind) AS (VALUES
      (1,'id_operacion_idempotente','bigint'::regtype::oid,-1,true,'d'::char),
      (2,'op_id','uuid'::regtype::oid,-1,true,''::char),
      (3,'command_code','varchar'::regtype::oid,104,true,''::char),
      (4,'target_type','varchar'::regtype::oid,104,true,''::char),
      (5,'target_uid','uuid'::regtype::oid,-1,false,''::char),
      (6,'target_key','varchar'::regtype::oid,204,false,''::char),
      (7,'payload_hash','character'::regtype::oid,68,true,''::char),
      (8,'canonicalization_version','integer'::regtype::oid,-1,true,''::char),
      (9,'result_code','varchar'::regtype::oid,104,true,''::char),
      (10,'result_http_status','integer'::regtype::oid,-1,false,''::char),
      (11,'result_target_uid','uuid'::regtype::oid,-1,false,''::char),
      (12,'result_version','integer'::regtype::oid,-1,false,''::char),
      (13,'response_snapshot','jsonb'::regtype::oid,-1,true,''::char),
      (14,'id_usuario','bigint'::regtype::oid,-1,false,''::char),
      (15,'id_sucursal','bigint'::regtype::oid,-1,false,''::char),
      (16,'id_instalacion','bigint'::regtype::oid,-1,true,''::char),
      (17,'created_at','timestamp without time zone'::regtype::oid,-1,true,''::char)
    )
    SELECT e.name INTO bad FROM expected e
    LEFT JOIN pg_attribute a ON a.attrelid='public.operacion_idempotente'::regclass
      AND a.attnum=e.attnum AND a.attname=e.name
    WHERE a.attname IS NULL OR a.atttypid<>e.type_oid OR a.atttypmod<>e.typmod
       OR a.attnotnull<>e.not_null OR a.attidentity<>e.identity_kind
       OR a.attgenerated<>'' OR a.attisdropped
    LIMIT 1;
    IF bad IS NOT NULL
       OR (SELECT count(*) FROM pg_attribute WHERE attrelid='public.operacion_idempotente'::regclass AND attnum>0) <> 17
    THEN RAISE EXCEPTION 'operacion_idempotente incompatible: catálogo físico de columnas'; END IF;

    IF (SELECT count(*)
          FROM pg_depend d
          JOIN pg_class seq ON seq.oid=d.objid AND d.classid='pg_class'::regclass
          JOIN pg_sequence s ON s.seqrelid=seq.oid
         WHERE d.refclassid='pg_class'::regclass
           AND d.refobjid='public.operacion_idempotente'::regclass
           AND d.refobjsubid=1 AND d.deptype='i'
           AND seq.relkind='S' AND seq.relpersistence='p'
           AND s.seqtypid='bigint'::regtype
           AND s.seqincrement=1 AND s.seqstart=1 AND s.seqmin=1
           AND s.seqmax=9223372036854775807 AND NOT s.seqcycle) <> 1
    THEN RAISE EXCEPTION 'operacion_idempotente incompatible: identity sequence contractual'; END IF;

    SELECT seq.oid INTO identity_sequence
      FROM pg_depend d
      JOIN pg_class seq ON seq.oid=d.objid AND d.classid='pg_class'::regclass
     WHERE d.refclassid='pg_class'::regclass
       AND d.refobjid='public.operacion_idempotente'::regclass
       AND d.refobjsubid=1 AND d.deptype='i';

    -- El ACCESS EXCLUSIVE sobre el ledger estabiliza el camino ordinario de
    -- INSERT antes de leer la secuencia. PostgreSQL no admite LOCK TABLE sobre
    -- sequences; el preflight no consume IDs ni altera su estado.
    EXECUTE format('SELECT last_value, is_called FROM %s', identity_sequence::regclass)
       INTO sequence_last_value, sequence_is_called;
    IF sequence_last_value < 1
       OR sequence_last_value > 9223372036854775807
       OR (sequence_is_called AND sequence_last_value >= 9223372036854775807)
    THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: identity sequence sin próximo valor utilizable';
    END IF;

    WITH expected(name, expression) AS (VALUES
      ('chk_operacion_idempotente_command_code',$pre$(btrim((command_code)::text, $pre$ || quote_literal(E' \t\n\r\f\x0B') || $post$::text) <> ''::text)$post$),
      ('chk_operacion_idempotente_target_type',$pre$(btrim((target_type)::text, $pre$ || quote_literal(E' \t\n\r\f\x0B') || $post$::text) <> ''::text)$post$),
      ('chk_operacion_idempotente_target_key',$pre$((target_key IS NULL) OR (btrim((target_key)::text, $pre$ || quote_literal(E' \t\n\r\f\x0B') || $post$::text) <> ''::text))$post$),
      ('chk_operacion_idempotente_payload_hash',$expr$(payload_hash ~ '^[0-9a-f]{64}$'::text)$expr$),
      ('chk_operacion_idempotente_canonicalization_version','(canonicalization_version >= 1)'),
      ('chk_operacion_idempotente_result_code',$pre$(btrim((result_code)::text, $pre$ || quote_literal(E' \t\n\r\f\x0B') || $post$::text) <> ''::text)$post$),
      ('chk_operacion_idempotente_result_http_status','((result_http_status IS NULL) OR ((result_http_status >= 100) AND (result_http_status <= 599)))'),
      ('chk_operacion_idempotente_result_version','((result_version IS NULL) OR (result_version >= 1))')
    ), actual AS (
      SELECT conname name, pg_get_expr(conbin,conrelid) expression FROM pg_constraint
       WHERE conrelid='public.operacion_idempotente'::regclass AND contype='c'
         AND convalidated AND NOT connoinherit AND conislocal AND coninhcount=0
    )
    SELECT coalesce(e.name,a.name) INTO bad FROM expected e FULL JOIN actual a USING (name)
     WHERE e.name IS NULL OR a.name IS NULL OR e.expression<>a.expression LIMIT 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: CHECK %', bad;
    END IF;

    -- PostgreSQL 18 incorpora pg_constraint.conenforced. La consulta debe ser
    -- dinámica para que PostgreSQL 16 nunca intente resolver esa columna.
    IF EXISTS (
        SELECT 1
          FROM pg_attribute
         WHERE attrelid='pg_catalog.pg_constraint'::regclass
           AND attname='conenforced' AND NOT attisdropped
    ) THEN
        EXECUTE $sql$
            SELECT conname
              FROM pg_constraint
             WHERE conrelid='public.operacion_idempotente'::regclass
               AND contype='c' AND NOT conenforced
             LIMIT 1
        $sql$ INTO bad;
        IF bad IS NOT NULL THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: CHECK % NOT ENFORCED', bad;
        END IF;
    END IF;

    IF (SELECT count(*) FROM pg_constraint WHERE conrelid='public.operacion_idempotente'::regclass) <> 13
       OR NOT EXISTS (
         SELECT 1 FROM pg_constraint c JOIN pg_index i ON i.indexrelid=c.conindid
          JOIN pg_class ic ON ic.oid=i.indexrelid JOIN pg_am am ON am.oid=ic.relam
          WHERE c.conrelid='public.operacion_idempotente'::regclass
            AND c.conname='operacion_idempotente_pkey' AND c.contype='p'
            AND NOT c.condeferrable AND NOT c.condeferred AND c.convalidated
            AND c.conislocal AND c.coninhcount=0
            AND c.conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname='id_operacion_idempotente')]::smallint[]
            AND i.indisprimary AND i.indisunique AND i.indimmediate
            AND i.indisvalid AND i.indisready AND i.indislive
            AND i.indpred IS NULL AND i.indexprs IS NULL
            AND i.indnkeyatts=1 AND i.indnatts=1 AND am.amname='btree'
            AND cardinality(i.indkey::smallint[])=1 AND (i.indkey::smallint[])[0]=c.conkey[1]
            AND cardinality(i.indclass::oid[])=1 AND (i.indclass::oid[])[0]=(SELECT o.oid FROM pg_opclass o JOIN pg_namespace n ON n.oid=o.opcnamespace JOIN pg_am a ON a.oid=o.opcmethod WHERE n.nspname='pg_catalog' AND o.opcname='int8_ops' AND a.amname='btree')
       )
       OR NOT EXISTS (
         SELECT 1 FROM pg_constraint c JOIN pg_index i ON i.indexrelid=c.conindid
          JOIN pg_class ic ON ic.oid=i.indexrelid JOIN pg_am am ON am.oid=ic.relam
          WHERE c.conrelid='public.operacion_idempotente'::regclass
            AND c.conname='uq_operacion_idempotente_op_id' AND c.contype='u'
            AND NOT c.condeferrable AND NOT c.condeferred AND c.convalidated
            AND c.conislocal AND c.coninhcount=0
            AND c.conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname='op_id')]::smallint[]
            AND NOT i.indisprimary AND i.indisunique AND i.indimmediate
            AND i.indisvalid AND i.indisready AND i.indislive
            AND i.indpred IS NULL AND i.indexprs IS NULL
            AND i.indnkeyatts=1 AND i.indnatts=1 AND am.amname='btree'
            AND cardinality(i.indkey::smallint[])=1 AND (i.indkey::smallint[])[0]=c.conkey[1]
            AND cardinality(i.indclass::oid[])=1 AND (i.indclass::oid[])[0]=(SELECT o.oid FROM pg_opclass o JOIN pg_namespace n ON n.oid=o.opcnamespace JOIN pg_am a ON a.oid=o.opcmethod WHERE n.nspname='pg_catalog' AND o.opcname='uuid_ops' AND a.amname='btree')
       ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: PK/UNIQUE o índices contractuales'; END IF;

    WITH expected(name, local_column, remote_table, remote_column) AS (VALUES
      ('fk_operacion_idempotente_usuario','id_usuario','public.usuario'::regclass,'id_usuario'),
      ('fk_operacion_idempotente_sucursal','id_sucursal','public.sucursal'::regclass,'id_sucursal'),
      ('fk_operacion_idempotente_instalacion','id_instalacion','public.instalacion'::regclass,'id_instalacion')
    )
    SELECT e.name INTO bad FROM expected e
     WHERE NOT EXISTS (
       SELECT 1 FROM pg_constraint c
        WHERE c.conrelid='public.operacion_idempotente'::regclass
          AND c.conname=e.name AND c.contype='f' AND c.confrelid=e.remote_table
          AND c.conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname=e.local_column)]::smallint[]
          AND c.confkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.confrelid AND attname=e.remote_column)]::smallint[]
          AND c.confdeltype='r' AND c.confupdtype='a' AND c.confmatchtype='s'
          AND NOT c.condeferrable AND NOT c.condeferred AND c.convalidated
          AND c.conislocal AND c.coninhcount=0
    ) LIMIT 1;
    IF bad IS NOT NULL THEN RAISE EXCEPTION 'operacion_idempotente incompatible: FK %', bad; END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_attribute
         WHERE attrelid='pg_catalog.pg_constraint'::regclass
           AND attname='conenforced' AND NOT attisdropped
    ) THEN
        EXECUTE $sql$
            SELECT conname
              FROM pg_constraint
             WHERE conrelid='public.operacion_idempotente'::regclass
               AND contype='f' AND NOT conenforced
             LIMIT 1
        $sql$ INTO bad;
        IF bad IS NOT NULL THEN
            RAISE EXCEPTION 'operacion_idempotente incompatible: FK % NOT ENFORCED', bad;
        END IF;
    END IF;

    WITH contractual_fk AS (
      SELECT c.oid, c.conname, c.conrelid, c.confrelid
        FROM pg_constraint c
       WHERE c.conrelid='public.operacion_idempotente'::regclass
         AND c.conname IN (
           'fk_operacion_idempotente_usuario',
           'fk_operacion_idempotente_sucursal',
           'fk_operacion_idempotente_instalacion'
         )
         AND c.contype='f'
    )
    SELECT fk.conname INTO bad
      FROM contractual_fk fk
      LEFT JOIN pg_trigger t ON t.tgconstraint=fk.oid
     GROUP BY fk.oid, fk.conname, fk.conrelid, fk.confrelid
    HAVING count(t.oid) <> 4
        OR count(t.oid) FILTER (WHERE t.tgisinternal AND t.tgenabled='O') <> 4
        OR count(t.oid) FILTER (WHERE t.tgrelid=fk.conrelid) <> 2
        OR count(t.oid) FILTER (WHERE t.tgrelid=fk.confrelid) <> 2
     LIMIT 1;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: mecanismos RI internos de FK %', bad;
    END IF;

    IF (SELECT count(*) FROM pg_index WHERE indrelid='public.operacion_idempotente'::regclass) <> 2 THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: índices adicionales o faltantes';
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='fn_assert_instalacion_pertenece_a_sucursal'
         AND p.proargtypes='20 20 25'::oidvector AND p.prorettype='void'::regtype
         AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND p.provolatile='v' AND NOT p.prosecdef AND NOT p.proisstrict
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$DECLARE
    v_ok BOOLEAN;
BEGIN
    IF p_id_instalacion IS NULL OR p_id_sucursal IS NULL THEN
        RETURN;
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM public.instalacion AS i
        WHERE i.id_instalacion = p_id_instalacion
          AND i.id_sucursal = p_id_sucursal
    ) INTO v_ok;

    IF NOT v_ok THEN
        RAISE EXCEPTION 'Inconsistencia sucursal/instalacion en %: instalacion % no pertenece a sucursal %',
            p_contexto, p_id_instalacion, p_id_sucursal;
    END IF;
END;$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: helper contractual sucursal/instalación'; END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='trg_operacion_idempotente_inmutable'
         AND p.pronargs=0 AND p.prorettype='trigger'::regtype AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND p.provolatile='v' AND NOT p.prosecdef AND NOT p.proisstrict
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$BEGIN
                RAISE EXCEPTION 'operacion_idempotente es inmutable: % no permitido', TG_OP;
            END$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: función de inmutabilidad'; END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
       WHERE n.nspname='public' AND p.proname='trg_operacion_idempotente_instalacion_sucursal'
         AND p.pronargs=0 AND p.prorettype='trigger'::regtype AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
         AND p.provolatile='v' AND NOT p.prosecdef AND NOT p.proisstrict
         AND regexp_replace(p.prosrc,'\s','','g') = regexp_replace($src$BEGIN
                PERFORM public.fn_assert_instalacion_pertenece_a_sucursal(
                    NEW.id_instalacion,
                    NEW.id_sucursal,
                    'operacion_idempotente'
                );
                RETURN NEW;
            END$src$,'\s','','g')
    ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: función de validación sucursal/instalación'; END IF;

    IF (SELECT count(*) FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass AND NOT tgisinternal) <> 3
       OR NOT EXISTS (
         SELECT 1 FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass
          AND tgname='trg_bud_operacion_idempotente_inmutable' AND NOT tgisinternal AND tgenabled='A'
          AND tgfoid='public.trg_operacion_idempotente_inmutable()'::regprocedure AND tgtype=27
          AND tgqual IS NULL AND cardinality(tgattr::smallint[])=0 AND tgparentid=0
       )
       OR NOT EXISTS (
         SELECT 1 FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass
          AND tgname='trg_bi_operacion_idempotente_instalacion_sucursal' AND NOT tgisinternal AND tgenabled='A'
          AND tgfoid='public.trg_operacion_idempotente_instalacion_sucursal()'::regprocedure AND tgtype=7
          AND tgqual IS NULL AND cardinality(tgattr::smallint[])=0 AND tgparentid=0
       )
       OR NOT EXISTS (
         SELECT 1 FROM pg_trigger WHERE tgrelid='public.operacion_idempotente'::regclass
          AND tgname='trg_bt_operacion_idempotente_inmutable' AND NOT tgisinternal AND tgenabled='A'
          AND tgfoid='public.trg_operacion_idempotente_inmutable()'::regprocedure AND tgtype=34
          AND tgqual IS NULL AND cardinality(tgattr::smallint[])=0 AND tgparentid=0
       ) THEN RAISE EXCEPTION 'operacion_idempotente incompatible: triggers contractuales'; END IF;

    IF EXISTS (
        SELECT 1
          FROM public.operacion_idempotente AS oi
          LEFT JOIN public.usuario AS u
            ON u.id_usuario=oi.id_usuario
          LEFT JOIN public.sucursal AS s
            ON s.id_sucursal=oi.id_sucursal
          LEFT JOIN public.instalacion AS i
            ON i.id_instalacion=oi.id_instalacion
         WHERE (oi.id_usuario IS NOT NULL AND u.id_usuario IS NULL)
            OR (oi.id_sucursal IS NOT NULL AND s.id_sucursal IS NULL)
            OR i.id_instalacion IS NULL
            OR (
                oi.id_sucursal IS NOT NULL
                AND i.id_sucursal IS DISTINCT FROM oi.id_sucursal
            )
         LIMIT 1
    ) THEN
        RAISE EXCEPTION 'operacion_idempotente incompatible: receipt histórico huérfano o con sucursal/instalación inconsistente';
    END IF;
END $$;

COMMIT;
