BEGIN;

CREATE TABLE IF NOT EXISTS public.comprobante_impuesto (
    id_comprobante_impuesto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_inmueble bigint,
    id_unidad_funcional bigint,
    organismo character varying(120) NOT NULL,
    tipo_impuesto character varying(80) NOT NULL,
    partida_nomenclatura character varying(120),
    numero_comprobante character varying(100) NOT NULL,
    periodo_desde date,
    periodo_hasta date,
    fecha_emision date,
    fecha_vencimiento date NOT NULL,
    importe_total numeric(14,2) NOT NULL,
    modalidad_gestion_impuesto character varying(40) NOT NULL,
    estado_comprobante_impuesto character varying(30) DEFAULT 'REGISTRADO'::character varying NOT NULL,
    observaciones text
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_estado'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_estado
            CHECK (estado_comprobante_impuesto IN ('REGISTRADO','ANULADO'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_fechas'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_fechas
            CHECK (fecha_emision IS NULL OR fecha_vencimiento >= fecha_emision);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_importe'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_importe
            CHECK (importe_total >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_modalidad'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_modalidad
            CHECK (modalidad_gestion_impuesto IN ('EMPRESA_ASUME','DIRECTO_RESPONSABLE','EMPRESA_PAGA_Y_RECUPERA'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_objeto_xor'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_objeto_xor
            CHECK (
                (id_inmueble IS NOT NULL AND id_unidad_funcional IS NULL)
                OR (id_inmueble IS NULL AND id_unidad_funcional IS NOT NULL)
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_comprobante_impuesto_periodo'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT chk_comprobante_impuesto_periodo
            CHECK (periodo_hasta IS NULL OR periodo_desde IS NULL OR periodo_hasta >= periodo_desde);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_comprobante_impuesto_uid_global'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT uq_comprobante_impuesto_uid_global UNIQUE (uid_global);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_comprobante_impuesto_inmueble'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT fk_comprobante_impuesto_inmueble
            FOREIGN KEY (id_inmueble)
            REFERENCES public.inmueble(id_inmueble)
            ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_comprobante_impuesto_unidad_funcional'
          AND conrelid = 'public.comprobante_impuesto'::regclass
    ) THEN
        ALTER TABLE public.comprobante_impuesto
            ADD CONSTRAINT fk_comprobante_impuesto_unidad_funcional
            FOREIGN KEY (id_unidad_funcional)
            REFERENCES public.unidad_funcional(id_unidad_funcional)
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_deleted_at
    ON public.comprobante_impuesto (deleted_at);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_fecha_vencimiento
    ON public.comprobante_impuesto (fecha_vencimiento);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_id_inmueble
    ON public.comprobante_impuesto (id_inmueble);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_id_unidad_funcional
    ON public.comprobante_impuesto (id_unidad_funcional);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_modalidad
    ON public.comprobante_impuesto (modalidad_gestion_impuesto);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_organismo
    ON public.comprobante_impuesto (organismo);

CREATE INDEX IF NOT EXISTS idx_comprobante_impuesto_uid_global
    ON public.comprobante_impuesto (uid_global);

CREATE UNIQUE INDEX IF NOT EXISTS ux_comprobante_impuesto_activo_organismo_numero
    ON public.comprobante_impuesto (organismo, numero_comprobante)
    WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_bi_comprobante_impuesto_core_ef ON public.comprobante_impuesto;
CREATE TRIGGER trg_bi_comprobante_impuesto_core_ef
    BEFORE INSERT ON public.comprobante_impuesto
    FOR EACH ROW
    EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();

DROP TRIGGER IF EXISTS trg_bu_comprobante_impuesto_core_ef ON public.comprobante_impuesto;
CREATE TRIGGER trg_bu_comprobante_impuesto_core_ef
    BEFORE UPDATE ON public.comprobante_impuesto
    FOR EACH ROW
    EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();

COMMIT;
