-- #255 Operativo: movimientos de caja.
-- Auditoría: no se encontró modelo operativo suficiente (movimiento_caja/caja_movimiento/caja_operativa_movimiento).
-- movimiento_tesoreria pertenece a tesorería/finanzas y no se reutiliza para caja operativa.

CREATE TABLE IF NOT EXISTS public.caja_operativa_movimiento (
    id_movimiento_caja bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_apertura_caja bigint NOT NULL,
    id_caja bigint NOT NULL,
    id_sucursal bigint NOT NULL,
    id_instalacion bigint NOT NULL,
    id_usuario_movimiento bigint,
    fecha_hora_movimiento timestamp without time zone NOT NULL,
    tipo_movimiento character varying(30) NOT NULL,
    concepto_movimiento character varying(80) NOT NULL,
    descripcion text,
    monto numeric(18,2) NOT NULL,
    moneda character varying(3) DEFAULT 'ARS' NOT NULL,
    sentido character varying(20) NOT NULL,
    estado_movimiento character varying(30) DEFAULT 'REGISTRADO' NOT NULL,
    observaciones text,
    CONSTRAINT chk_caja_operativa_movimiento_tipo CHECK (tipo_movimiento IN ('INGRESO', 'EGRESO', 'AJUSTE')),
    CONSTRAINT chk_caja_operativa_movimiento_sentido CHECK (sentido IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT chk_caja_operativa_movimiento_estado CHECK (estado_movimiento IN ('REGISTRADO', 'ANULADO')),
    CONSTRAINT chk_caja_operativa_movimiento_moneda CHECK (moneda IN ('ARS', 'USD')),
    CONSTRAINT chk_caja_operativa_movimiento_monto CHECK (monto > 0),
    CONSTRAINT chk_caja_operativa_movimiento_tipo_sentido CHECK (
        (tipo_movimiento = 'INGRESO' AND sentido = 'ENTRADA') OR
        (tipo_movimiento = 'EGRESO' AND sentido = 'SALIDA') OR
        (tipo_movimiento = 'AJUSTE' AND sentido IN ('ENTRADA', 'SALIDA'))
    ),
    CONSTRAINT fk_caja_operativa_movimiento_apertura FOREIGN KEY (id_apertura_caja) REFERENCES public.caja_operativa_apertura(id_apertura_caja) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_movimiento_caja FOREIGN KEY (id_caja) REFERENCES public.caja_operativa(id_caja) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_movimiento_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_movimiento_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_movimiento_uid_global ON public.caja_operativa_movimiento (uid_global);
CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_movimiento_op_id_alta ON public.caja_operativa_movimiento (op_id_alta) WHERE op_id_alta IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_apertura ON public.caja_operativa_movimiento (id_apertura_caja);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_caja ON public.caja_operativa_movimiento (id_caja);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_sucursal ON public.caja_operativa_movimiento (id_sucursal);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_instalacion ON public.caja_operativa_movimiento (id_instalacion);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_fecha ON public.caja_operativa_movimiento (fecha_hora_movimiento);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_tipo ON public.caja_operativa_movimiento (tipo_movimiento);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_sentido ON public.caja_operativa_movimiento (sentido);
CREATE INDEX IF NOT EXISTS ix_caja_operativa_movimiento_estado ON public.caja_operativa_movimiento (estado_movimiento);
