-- #252 Operativo: configuración local por sucursal/instalación.
-- Auditoría: valor_parametro existe, pero no posee metadata CORE-EF completa,
-- idempotencia por op_id ni versionado para writes sincronizables. Se crea una
-- tabla operativa mínima y acotada para configuración local.

CREATE TABLE IF NOT EXISTS public.configuracion_local (
    id_configuracion_local bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_sucursal bigint NOT NULL,
    id_instalacion bigint NOT NULL,
    clave_configuracion character varying(100) NOT NULL,
    valor_configuracion text,
    tipo_valor character varying(30) NOT NULL,
    descripcion text,
    estado_configuracion character varying(30) DEFAULT 'ACTIVA'::character varying NOT NULL,
    CONSTRAINT chk_configuracion_local_deleted_at CHECK ((deleted_at IS NULL) OR (deleted_at >= created_at)),
    CONSTRAINT chk_configuracion_local_tipo_valor CHECK (tipo_valor IN ('TEXTO','NUMERO','DECIMAL','BOOLEANO','FECHA','JSON')),
    CONSTRAINT chk_configuracion_local_estado CHECK (estado_configuracion IN ('ACTIVA','INACTIVA')),
    CONSTRAINT fk_configuracion_local_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
    CONSTRAINT fk_configuracion_local_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_configuracion_local_uid_global
    ON public.configuracion_local (uid_global);

CREATE UNIQUE INDEX IF NOT EXISTS ux_configuracion_local_op_id_alta
    ON public.configuracion_local (op_id_alta)
    WHERE op_id_alta IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_configuracion_local_clave_activa
    ON public.configuracion_local (id_sucursal, id_instalacion, clave_configuracion)
    WHERE deleted_at IS NULL AND estado_configuracion = 'ACTIVA';

CREATE INDEX IF NOT EXISTS ix_configuracion_local_contexto
    ON public.configuracion_local (id_sucursal, id_instalacion);
