-- #254 Operativo: apertura y cierre de caja.
-- Auditoría: no se encontró modelo suficiente apertura_caja/caja_apertura/caja_sesion/caja_operativa_apertura/jornada_caja; se crea tabla acotada del dominio operativo.

CREATE TABLE IF NOT EXISTS public.caja_operativa_apertura (
    id_apertura_caja bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_caja bigint NOT NULL,
    id_sucursal bigint NOT NULL,
    id_instalacion bigint NOT NULL,
    id_usuario_apertura bigint,
    id_usuario_cierre bigint,
    fecha_hora_apertura timestamp without time zone NOT NULL,
    fecha_hora_cierre timestamp without time zone,
    saldo_inicial numeric(18,2) DEFAULT 0 NOT NULL,
    saldo_declarado_cierre numeric(18,2),
    moneda character varying(3) DEFAULT 'ARS' NOT NULL,
    estado_apertura character varying(30) DEFAULT 'ABIERTA' NOT NULL,
    observaciones_apertura text,
    observaciones_cierre text,
    CONSTRAINT chk_caja_operativa_apertura_estado CHECK (estado_apertura IN ('ABIERTA', 'CERRADA', 'ANULADA')),
    CONSTRAINT chk_caja_operativa_apertura_moneda CHECK (moneda IN ('ARS', 'USD')),
    CONSTRAINT chk_caja_operativa_apertura_saldo_inicial CHECK (saldo_inicial >= 0),
    CONSTRAINT chk_caja_operativa_apertura_saldo_cierre CHECK (saldo_declarado_cierre IS NULL OR saldo_declarado_cierre >= 0),
    CONSTRAINT chk_caja_operativa_apertura_fechas CHECK (fecha_hora_cierre IS NULL OR fecha_hora_cierre >= fecha_hora_apertura),
    CONSTRAINT fk_caja_operativa_apertura_caja FOREIGN KEY (id_caja) REFERENCES public.caja_operativa(id_caja) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_apertura_sucursal FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal) ON DELETE RESTRICT,
    CONSTRAINT fk_caja_operativa_apertura_instalacion FOREIGN KEY (id_instalacion) REFERENCES public.instalacion(id_instalacion) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_apertura_uid_global
    ON public.caja_operativa_apertura (uid_global);

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_apertura_op_id_alta
    ON public.caja_operativa_apertura (op_id_alta)
    WHERE op_id_alta IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_caja_operativa_apertura_vigente_caja
    ON public.caja_operativa_apertura (id_caja)
    WHERE deleted_at IS NULL AND estado_apertura = 'ABIERTA' AND fecha_hora_cierre IS NULL;

CREATE INDEX IF NOT EXISTS ix_caja_operativa_apertura_sucursal
    ON public.caja_operativa_apertura (id_sucursal);

CREATE INDEX IF NOT EXISTS ix_caja_operativa_apertura_instalacion
    ON public.caja_operativa_apertura (id_instalacion);

CREATE INDEX IF NOT EXISTS ix_caja_operativa_apertura_caja
    ON public.caja_operativa_apertura (id_caja);

CREATE INDEX IF NOT EXISTS ix_caja_operativa_apertura_estado
    ON public.caja_operativa_apertura (estado_apertura);

CREATE INDEX IF NOT EXISTS ix_caja_operativa_apertura_fecha_apertura
    ON public.caja_operativa_apertura (fecha_hora_apertura);
