-- Patch idempotente: soporte V1 de responsables de servicios trasladados.

CREATE TABLE IF NOT EXISTS public.asignacion_servicio_responsable (
    id_asignacion_servicio_responsable bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_global uuid DEFAULT gen_random_uuid() NOT NULL,
    version_registro integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    id_instalacion_origen bigint,
    id_instalacion_ultima_modificacion bigint,
    op_id_alta uuid,
    op_id_ultima_modificacion uuid,
    id_servicio bigint NOT NULL,
    id_inmueble bigint,
    id_unidad_funcional bigint,
    id_persona bigint NOT NULL,
    porcentaje_responsabilidad numeric(5,2) NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date,
    estado_asignacion character varying(30) DEFAULT 'ACTIVA'::character varying NOT NULL,
    observaciones text
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_asr_objeto_xor') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT chk_asr_objeto_xor
            CHECK ((((id_inmueble IS NOT NULL) AND (id_unidad_funcional IS NULL)) OR ((id_inmueble IS NULL) AND (id_unidad_funcional IS NOT NULL))));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_asr_porcentaje') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT chk_asr_porcentaje
            CHECK (((porcentaje_responsabilidad > (0)::numeric) AND (porcentaje_responsabilidad <= (100)::numeric)));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_asr_vigencia') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT chk_asr_vigencia
            CHECK (((fecha_hasta IS NULL) OR (fecha_hasta >= fecha_desde)));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_asr_estado') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT chk_asr_estado
            CHECK (((estado_asignacion)::text = ANY ((ARRAY['ACTIVA'::character varying, 'INACTIVA'::character varying])::text[])));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_asignacion_servicio_responsable_uid_global') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT uq_asignacion_servicio_responsable_uid_global UNIQUE (uid_global);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asr_servicio') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT fk_asr_servicio FOREIGN KEY (id_servicio) REFERENCES public.servicio(id_servicio) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asr_inmueble') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT fk_asr_inmueble FOREIGN KEY (id_inmueble) REFERENCES public.inmueble(id_inmueble) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asr_unidad_funcional') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT fk_asr_unidad_funcional FOREIGN KEY (id_unidad_funcional) REFERENCES public.unidad_funcional(id_unidad_funcional) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asr_persona') THEN
        ALTER TABLE public.asignacion_servicio_responsable
            ADD CONSTRAINT fk_asr_persona FOREIGN KEY (id_persona) REFERENCES public.persona(id_persona) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_asr_servicio_inmueble_vigencia
    ON public.asignacion_servicio_responsable USING btree (id_servicio, id_inmueble, fecha_desde, fecha_hasta);
CREATE INDEX IF NOT EXISTS idx_asr_servicio_unidad_vigencia
    ON public.asignacion_servicio_responsable USING btree (id_servicio, id_unidad_funcional, fecha_desde, fecha_hasta);
CREATE INDEX IF NOT EXISTS idx_asr_persona
    ON public.asignacion_servicio_responsable USING btree (id_persona);
CREATE INDEX IF NOT EXISTS idx_asr_uid_global
    ON public.asignacion_servicio_responsable USING btree (uid_global);

DROP TRIGGER IF EXISTS trg_bi_asignacion_servicio_responsable_core_ef
    ON public.asignacion_servicio_responsable;
CREATE TRIGGER trg_bi_asignacion_servicio_responsable_core_ef
    BEFORE INSERT ON public.asignacion_servicio_responsable
    FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_insert();

DROP TRIGGER IF EXISTS trg_bu_asignacion_servicio_responsable_core_ef
    ON public.asignacion_servicio_responsable;
CREATE TRIGGER trg_bu_asignacion_servicio_responsable_core_ef
    BEFORE UPDATE ON public.asignacion_servicio_responsable
    FOR EACH ROW EXECUTE FUNCTION public.trg_core_ef_sync_defaults_update();
